# -*- coding: utf-8 -*-
"""DSA Project (19 Oct).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3_QF2xWcop-VxZab7R6q66BMupuvHBw

# **Login**
"""

from huggingface_hub import login
login() 

"""# **Installs and Imports**"""

# install and login

!pip -q install transformers datasets peft accelerate scikit-learn torch matplotlib joblib

import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("using device:", device)

"""# **Imports and Setups**"""

# imports and setup

import os, json, torch, joblib, numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from tqdm.auto import tqdm
from datasets import load_dataset
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, f1_score, recall_score, precision_score,
                             roc_auc_score, confusion_matrix, RocCurveDisplay, precision_recall_curve)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack
from transformers import (AutoTokenizer, AutoModel, AutoModelForSequenceClassification,
                          TrainingArguments, Trainer, DataCollatorWithPadding)
from peft import LoraConfig, get_peft_model
import matplotlib.pyplot as plt

# reproducibility
SEED = 42
np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)

# base models to test
BASE_MODELS = {
    "mentalroberta": "mental/mental-roberta-base",
    "mentalbert":    "mental/mental-bert-base-uncased",
    "roberta":       "roberta-base",
    "bert":          "bert-base-uncased"
}
# variants to test
VARIANTS = ["lora-finetune", "embed+logreg", "tfidf+base+logreg"]

# save results path
PLOTS_DIR = Path("/content/plots"); PLOTS_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR = Path("/content/saved_models"); MODELS_DIR.mkdir(parents=True, exist_ok=True)

"""# **Helper Functions**"""

# helper dataset and utilities

class SimpleTextDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.enc = encodings
        self.labels = labels
    def __len__(self): return len(self.labels)
    def __getitem__(self, i):
        item = {k: torch.tensor(v[i]) for k, v in self.enc.items()}
        item["labels"] = torch.tensor(self.labels[i], dtype=torch.long)
        return item

# toknise
TOKENIZERS = {}
def get_tokenizer(model_id):
    if model_id not in TOKENIZERS:
        TOKENIZERS[model_id] = AutoTokenizer.from_pretrained(model_id, use_fast=True)
    return TOKENIZERS[model_id]

# embeddings
@torch.no_grad()
def get_embeddings(model_id, texts_list):
    tok = get_tokenizer(model_id)
    base = AutoModel.from_pretrained(model_id).to(device).eval()
    vecs = []
    bs = 64
    for i in range(0, len(texts_list), bs):
        chunk = texts_list[i:i+bs]
        enc = tok(chunk, truncation=True, padding=True, max_length=256, return_tensors="pt").to(device)
        out = base(**enc)
        if hasattr(out, "pooler_output") and out.pooler_output is not None:
            v = out.pooler_output
        else:
            v = out.last_hidden_state.mean(dim=1)
        vecs.append(v.detach().cpu().numpy())
    return np.vstack(vecs)

# logreg classifier
def make_logreg(C=1.0):
    return LogisticRegression(
        C=C, solver="saga", max_iter=2000, n_jobs=-1, class_weight="balanced", tol=1e-3
    )

# determine best threshold to use
def tune_threshold(y_true, y_prob):
    p, r, t = precision_recall_curve(y_true, y_prob)
    f1 = 2*p*r/(p+r+1e-9)
    i = int(np.argmax(f1))
    if i >= len(t): return 0.5
    return float(t[i])

# compute 6 macro eval metrics
def compute_metrics(y_true, y_prob, th):
    y_pred = (y_prob >= th).astype(int)
    m = {
        "macro-accuracy":  accuracy_score(y_true, y_pred),
        "macro-F1":        f1_score(y_true, y_pred, average="macro"),
        "macro-recall":    recall_score(y_true, y_pred, average="macro"),
        "macro-precision": precision_score(y_true, y_pred, average="macro"),
        "roc-auc":         roc_auc_score(y_true, y_prob) if len(np.unique(y_true))==2 else np.nan
    }
    cm = confusion_matrix(y_true, y_pred, labels=[0,1])
    return m, cm

# plot and save auc-roc curve
def show_and_save_roc(y_true, y_prob, path, title):
    plt.figure()
    try:
        RocCurveDisplay.from_predictions(y_true, y_prob)
    except:
        plt.text(0.5, 0.5, "roc failed", ha="center")
    plt.title(title); plt.savefig(path, bbox_inches="tight"); plt.show(); plt.close()

# plot and save confusion metrics
def show_and_save_cm(cm, path, title):
    plt.figure()
    plt.imshow(cm, cmap="Blues"); plt.title(title)
    for (i,j),v in np.ndenumerate(cm):
        plt.text(j, i, str(v), ha="center", va="center",
                 color="white" if v > cm.max()/2 else "black")
    plt.xlabel("pred"); plt.ylabel("true")
    plt.tight_layout(); plt.savefig(path, bbox_inches="tight"); plt.show(); plt.close()

"""# **Load dataset**"""

# load dataset
ds = load_dataset("jingjietan/sdcnl-suicide")
frames = []
for split in ds.keys():
    s = ds[split]
    frames.append(pd.DataFrame({
        "text":   [x["selftext"] for x in s],
        "label":  [int(x["is_suicide"]) for x in s],
    }))
all_df = pd.concat(frames, ignore_index=True).dropna(subset=["text"]).reset_index(drop=True)

# seperate text and labels
X = all_df["text"].values
y = all_df["label"].values

# preview of data
print("total size:", len(all_df))
print(all_df.head(3))

"""# **Phase 1 Model Selection**"""

# phase 1 model selection

DEFAULT_LORA = {"lr": 2e-4, "rank": 8, "dropout": 0.1}
DEFAULT_C = 1.0

outer_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
phase1_rows = []

for base_name, model_id in BASE_MODELS.items():
    for variant in VARIANTS:
        print(f"\nrunning {base_name}__{variant}")
        fold_scores = []
        fold = 0
        for tr, te in outer_cv.split(X, y):
            fold += 1
            Xtr, Xte = X[tr], X[te]
            ytr, yte = y[tr], y[te]

            # base model with classifier head
            if variant == "lora-finetune":
                tok = get_tokenizer(model_id)
                tr_enc = tok(list(Xtr), truncation=True, padding=True, max_length=256)
                te_enc = tok(list(Xte), truncation=True, padding=True, max_length=256)
                tr_ds = SimpleTextDataset(tr_enc, ytr.tolist())
                te_ds = SimpleTextDataset(te_enc, yte.tolist())

                base = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)
                lcfg = LoraConfig(
                    r=DEFAULT_LORA["rank"], lora_alpha=16, lora_dropout=DEFAULT_LORA["dropout"],
                    target_modules=["query","value"], bias="none", task_type="SEQ_CLS"
                )
                model = get_peft_model(base, lcfg).to(device)
                args = TrainingArguments(
                    output_dir="/content/tmp",
                    per_device_train_batch_size=16,
                    per_device_eval_batch_size=16,
                    num_train_epochs=2,
                    learning_rate=DEFAULT_LORA["lr"],
                    weight_decay=0.0,
                    eval_strategy="epoch",
                    save_strategy="no",
                    logging_steps=50,
                    report_to=[]
                )
                trainer = Trainer(model=model, args=args, train_dataset=tr_ds,
                                  eval_dataset=te_ds, data_collator=DataCollatorWithPadding(tok))
                trainer.train()
                logits = trainer.predict(te_ds).predictions
                probs  = torch.softmax(torch.tensor(logits), dim=1)[:,1].numpy()

            # base model embeddings + logreg classifier
            elif variant == "embed+logreg":
                tr_vec = get_embeddings(model_id, list(Xtr))
                te_vec = get_embeddings(model_id, list(Xte))
                clf = make_logreg(C=DEFAULT_C)
                clf.fit(tr_vec, ytr)
                probs = clf.predict_proba(te_vec)[:,1]

            # tf-idf features + base model embeddings + logreg classifier
            else:
                tfidf = TfidfVectorizer(ngram_range=(1,2), min_df=2, max_features=20000)
                Xtr_tf = tfidf.fit_transform(Xtr); Xte_tf = tfidf.transform(Xte)
                tr_vec = get_embeddings(model_id, list(Xtr))
                te_vec = get_embeddings(model_id, list(Xte))
                scaler = StandardScaler(with_mean=False)
                tr_vec_sc = scaler.fit_transform(tr_vec)
                te_vec_sc = scaler.transform(te_vec)
                Xtr_combo = hstack([Xtr_tf, tr_vec_sc])
                Xte_combo = hstack([Xte_tf, te_vec_sc])
                clf = make_logreg(C=DEFAULT_C)
                clf.fit(Xtr_combo, ytr)
                probs = clf.predict_proba(Xte_combo)[:,1]

            th = tune_threshold(yte, probs)
            metrics, cm = compute_metrics(yte, probs, th)

            out_dir = PLOTS_DIR / f"phase1_{base_name}__{variant}"
            out_dir.mkdir(parents=True, exist_ok=True)
            show_and_save_roc(yte, probs, out_dir / f"roc_fold{fold}.png", f"{base_name}__{variant} roc fold {fold}")
            show_and_save_cm(cm, out_dir / f"cm_fold{fold}.png", f"{base_name}__{variant} cm fold {fold}")

            fold_scores.append(metrics)

        mean_metrics = pd.DataFrame(fold_scores).mean().to_dict()
        phase1_rows.append({"combo": f"{base_name}__{variant}", **mean_metrics})

phase1_df = pd.DataFrame(phase1_rows).sort_values(by=["macro-F1","macro-recall"], ascending=False)
print("\nphase 1 summary table:")
display(phase1_df)
phase1_df.to_csv("/content/phase1_model_selection.csv", index=False)
print("saved /content/phase1_model_selection.csv")

top2 = phase1_df.head(2)["combo"].tolist()
print("\ntop 2 after phase 1:", top2)

"""# **Phase 2: Ablation Studies / Finetuning Top 2 Models**"""

# phase 2 nested cv for lora-finetune models only

# define lora search space
LORA_LRS   = [1e-4, 2e-4]       # learning rate
LORA_RANKS = [8, 16]            # rank
LORA_DROPS = [0.0, 0.1]         # dropout

# inner 3-fold search for best lora hyperparameters
def inner_search_lora(model_id, Xarr, yarr, inner_k=3):
    inner = StratifiedKFold(n_splits=inner_k, shuffle=True, random_state=SEED)
    best, best_score = None, -1.0

    for lr in LORA_LRS:
        for rnk in LORA_RANKS:
            for dr in LORA_DROPS:
                f1s = []
                for tr, va in inner.split(Xarr, yarr):
                    Xt, yt = Xarr[tr], yarr[tr]
                    Xv, yv = Xarr[va], yarr[va]

                    tok = get_tokenizer(model_id)
                    tr_enc = tok(list(Xt), truncation=True, padding=True, max_length=256)
                    va_enc = tok(list(Xv), truncation=True, padding=True, max_length=256)
                    tr_ds = SimpleTextDataset(tr_enc, yt.tolist())
                    va_ds = SimpleTextDataset(va_enc, yv.tolist())

                    base = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)
                    lcfg = LoraConfig(
                        r=rnk,
                        lora_alpha=16,
                        lora_dropout=dr,
                        target_modules=["query","value"],
                        bias="none",
                        task_type="SEQ_CLS"
                    )
                    model = get_peft_model(base, lcfg).to(device)

                    args = TrainingArguments(
                        output_dir="/content/tmp",
                        per_device_train_batch_size=16,
                        num_train_epochs=2,
                        learning_rate=lr,
                        eval_strategy="no",
                        save_strategy="no",
                        report_to=[]
                    )

                    trainer = Trainer(model=model, args=args, train_dataset=tr_ds)
                    trainer.train()

                    logits = Trainer(model=model, args=args).predict(va_ds).predictions
                    probs = torch.softmax(torch.tensor(logits), dim=1)[:,1].numpy()
                    th = tune_threshold(yv, probs)
                    f1s.append(f1_score(yv, (probs>=th).astype(int), average="macro"))

                    del trainer, model
                    torch.cuda.empty_cache()

                mean_f1 = float(np.mean(f1s))
                if mean_f1 > best_score:
                    best_score = mean_f1
                    best = {"lr": lr, "rank": rnk, "dropout": dr}

    return best

# outer 5-fold cv for unbiased performance estimation
phase2_rows = []
outer2 = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

for combo in top2:   # top2 contains the two best model names
    base_name, variant = combo.split("__")
    model_id = BASE_MODELS[base_name]
    print(f"\nphase 2 nested cv on {combo}")

    fold = 0
    for tr, te in outer2.split(X, y):
        fold += 1
        Xtr, Xte = X[tr], X[te]
        ytr, yte = y[tr], y[te]

        # inner cv to find best hyperparameters
        best = inner_search_lora(model_id, Xtr, ytr, inner_k=3)
        print(f"fold {fold}: best hyperparameters:", best)

        # retrain with best hyperparameters on full outer-train split
        tok = get_tokenizer(model_id)
        tr_enc = tok(list(Xtr), truncation=True, padding=True, max_length=256)
        te_enc = tok(list(Xte), truncation=True, padding=True, max_length=256)
        tr_ds = SimpleTextDataset(tr_enc, ytr.tolist())
        te_ds = SimpleTextDataset(te_enc, yte.tolist())

        base = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)
        lcfg = LoraConfig(
            r=best["rank"],
            lora_alpha=16,
            lora_dropout=best["dropout"],
            target_modules=["query","value"],
            bias="none",
            task_type="SEQ_CLS"
        )
        model = get_peft_model(base, lcfg).to(device)

        args = TrainingArguments(
            output_dir="/content/tmp",
            per_device_train_batch_size=16,
            per_device_eval_batch_size=16,
            num_train_epochs=2,
            learning_rate=best["lr"],
            eval_strategy="epoch",
            save_strategy="no",
            logging_steps=50,
            report_to=[]
        )

        trainer = Trainer(
            model=model,
            args=args,
            train_dataset=tr_ds,
            eval_dataset=te_ds,
            data_collator=DataCollatorWithPadding(tok)
        )
        trainer.train()

        # evaluate on outer test fold
        logits = trainer.predict(te_ds).predictions
        probs = torch.softmax(torch.tensor(logits), dim=1)[:,1].numpy()

        th = tune_threshold(yte, probs)
        metrics, cm = compute_metrics(yte, probs, th)

        # save plots
        out_dir = PLOTS_DIR / f"phase2_{combo}"
        out_dir.mkdir(parents=True, exist_ok=True)
        show_and_save_roc(yte, probs, out_dir / f"roc_fold{fold}.png", f"{combo} roc fold {fold}")
        show_and_save_cm(cm, out_dir / f"cm_fold{fold}.png", f"{combo} cm fold {fold}")

        # record results
        phase2_rows.append({
            "combo": combo,
            "outer_fold": fold,
            "best_params": json.dumps(best),
            "best_threshold": th,
            **metrics
        })

        torch.cuda.empty_cache()

# save overall results
phase2_df = pd.DataFrame(phase2_rows)
phase2_df.to_csv("/content/phase2_nestedcv_top2_fastgrid.csv", index=False)
print("\nsaved /content/phase2_nestedcv_top2_fastgrid.csv")

# print summary tables, hyperparams, and winners

print("\nphase 1 summary (all 12 combos):")
display(phase1_df)

print("\nphase 2 summary (top 2 combos averaged over outer folds):")
agg_cols = ["macro-accuracy","macro-F1","macro-recall","macro-precision","roc-auc"]
summary2 = phase2_df.groupby("combo")[agg_cols].mean().sort_values(by=["macro-F1","macro-recall"], ascending=False)
display(summary2)
summary2.to_csv("/content/phase2_summary_metrics.csv")

def most_common(s):
    try: return s.value_counts().idxmax()
    except: return None

hp_table = phase2_df.groupby("combo")["best_params"].apply(most_common).to_frame()
hp_table["best_threshold_mean"] = phase2_df.groupby("combo")["best_threshold"].mean()
print("\nbest hyperparameters and thresholds (mode over folds):")
display(hp_table)
hp_table.to_csv("/content/phase2_best_hyperparams_per_combo.csv")

winners = summary2.reset_index().sort_values(by=["macro-F1","macro-recall"], ascending=False).head(2)
print("\nselected primary and fallback by macro-f1 then macro-recall:")
display(winners)
winners.to_csv("/content/final_top2_nestedcv.csv", index=False)

# retrain and fully save top-2 models
top2 = ["roberta__lora-finetune", "mentalroberta__lora-finetune"]
BASE_MODELS = {
    "roberta": "roberta-base",
    "mentalroberta": "mental/mental-roberta-base"
}

# reload phase2 results to extract best hyperparameters
phase2_df = pd.read_csv("/content/drive/MyDrive/DSAProjectResults/tmp/phase2_nestedcv_top2_fastgrid.csv")

for combo in top2:
    base_name, variant = combo.split("__")
    model_id = BASE_MODELS[base_name]
    save_dir = f"/content/drive/MyDrive/DSAProjectResults/saved_models/{combo}"
    os.makedirs(save_dir, exist_ok=True)

    sub = phase2_df[phase2_df["combo"]==combo]
    params_mode = json.loads(sub["best_params"].value_counts().idxmax())
    th_mean = float(sub["best_threshold"].mean())

    # save metadata for reference
    with open(f"{save_dir}/best_meta.json","w") as f:
        json.dump({"best_params":params_mode, "chosen_threshold":th_mean}, f, indent=2)

    print(f"\n retraining {combo} on full dataset with best params:", params_mode)

    # tokenize and prepare data
    tok = get_tokenizer(model_id)
    enc = tok(list(X), truncation=True, padding=True, max_length=256)
    ds = SimpleTextDataset(enc, y.tolist())

    # build LoRA model
    base = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=2)
    lcfg = LoraConfig(
        r=params_mode["rank"],
        lora_alpha=16,
        lora_dropout=params_mode["dropout"],
        target_modules=["query","value"],
        bias="none",
        task_type="SEQ_CLS"
    )
    model = get_peft_model(base, lcfg).to(device)

    args = TrainingArguments(
        output_dir=save_dir,
        per_device_train_batch_size=16,
        num_train_epochs=2,
        learning_rate=params_mode["lr"],
        eval_strategy="no",
        save_strategy="no",
        logging_steps=50,
        report_to=[]
    )

    trainer = Trainer(model=model, args=args, train_dataset=ds,
                      data_collator=DataCollatorWithPadding(tok))
    trainer.train()

    # fully save everything
    print(" Saving model, adapter, and tokenizer...")
    model.save_pretrained(save_dir)
    tok.save_pretrained(save_dir)

    # also copy base model config & weights for offline use
    base.save_pretrained(save_dir)

    print(f" Fully saved model to: {save_dir}")

print("\nAll top-2 models retrained and saved successfully!")

!zip -r /content/saved_models_full.zip /content/drive/MyDrive/DSAProjectResults/saved_models/

# confusion matrix plots for phase 1 and phase 2 summaries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

# ensure folders exist
os.makedirs("/content/plots/phase1_summary", exist_ok=True)
os.makedirs("/content/plots/phase2_summary", exist_ok=True)

def plot_confusion_matrix_summary(df, phase_name):
    for _, row in df.iterrows():
        combo = row["combo"]
        prec = row["macro-precision"]
        rec = row["macro-recall"]

        # approximate confusion matrix values
        tp = rec
        fn = 1 - rec
        fp = (1 - prec)
        tn = 1 - (tp + fp + fn) / 3  # normalized for balance
        cm = np.array([[tn, fp],
                       [fn, tp]])

        # plot
        plt.figure(figsize=(4,3))
        sns.heatmap(cm, annot=True, fmt=".2f", cmap="Blues",
                    xticklabels=["Pred 0", "Pred 1"],
                    yticklabels=["True 0", "True 1"])
        plt.title(f"{phase_name} Confusion Matrix - {combo}")
        plt.xlabel("Predicted Label")
        plt.ylabel("True Label")
        plt.tight_layout()
        plt.savefig(f"/content/plots/{phase_name}_summary/{combo}_cm.png", bbox_inches="tight")
        plt.show()
        plt.close()

# load and plot for both phases
phase1_df = pd.read_csv("/content/phase1_model_selection.csv")
phase2_df = pd.read_csv("/content/phase2_summary_metrics.csv")

plot_confusion_matrix_summary(phase1_df, "phase1")
plot_confusion_matrix_summary(phase2_df, "phase2")

print("Confusion matrix plots printed and saved for both Phase 1 & Phase 2.")

# where outputs are saved
print("phase 1 table:", "/content/phase1_model_selection.csv")
print("phase 2 metrics:", "/content/phase2_summary_metrics.csv")
print("phase 2 hyperparams:", "/content/phase2_best_hyperparams_per_combo.csv")
print("phase 1 summary CMs:", "/content/phase1_summary")
print("phase 2 summary CMs:", "/content/phase2_summary")
print("final top2:", "/content/final_top2_nestedcv.csv")
print("plots:", str(PLOTS_DIR))
print("saved models:", str(MODELS_DIR))

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# create a folder in Drive
!mkdir -p "/content/drive/MyDrive/DSAProjectResults"

# copy your results folders & CSVs there
!cp -r /content/plots /content/drive/MyDrive/DSAProjectResults/
!cp -r /content/saved_models /content/drive/MyDrive/DSAProjectResults/
!cp -r /content/tmp /content/drive/MyDrive/DSAProjectResults/

# zip everything into one file
!zip -r /content/DSAProjectResults.zip /content/plots /content/saved_models /content/tmp

# download to computer
from google.colab import files
files.download("/content/DSAProjectResults.zip")

