# -*- coding: utf-8 -*-
"""DSA Project (21 Oct) - SafetyCheckClass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u48TRxZxQPFvdspOWpqUQhPFXEWBIOds
"""

import os
import random
import json
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig
from peft import PeftModel

# enforce offline mode
os.environ["TRANSFORMERS_OFFLINE"] = "1"
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["HF_DATASETS_OFFLINE"] = "1"
os.environ["HF_HUB_DISABLE_TELEMETRY"] = "1"
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

# reproducibility
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
torch.use_deterministic_algorithms(True, warn_only=True)
torch.cuda.empty_cache()

# SafetyCheck.py
class SafetyCheck:
    """
    SafetyCheck(text) → returns 0 (not at risk) or 1 (at risk)

    Primary model:   RoBERTa (fine-tuned LoRA)
    Fallback model:  MentalRoBERTa (fine-tuned LoRA)
    """

    def __init__(self, base_dir="saved_models"):
        """
        Loads both primary and fallback models from the local saved_models folder.
        """
        self.base_dir = base_dir
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # define model paths
        self.primary_path = os.path.join(base_dir, "roberta__lora-finetune")
        self.fallback_path = os.path.join(base_dir, "mentalroberta__lora-finetune")

        # load models
        print(f"using base directory: {self.base_dir}")
        print("loading primary model (roberta)...")
        self.primary_model, self.primary_tokenizer = self._load_model(self.primary_path)

        print("loading fallback model (mentalroberta)...")
        self.fallback_model, self.fallback_tokenizer = self._load_model(self.fallback_path)

        # load tuned thresholds from metadata
        self.primary_threshold = self._load_threshold(self.primary_path)
        self.fallback_threshold = self._load_threshold(self.fallback_path)
        print(f"loaded thresholds → primary={self.primary_threshold:.3f}, fallback={self.fallback_threshold:.3f}\n")


    def _load_model(self, model_path):
        if not os.path.exists(model_path):
            raise FileNotFoundError(f"model folder not found: {model_path}")

        print(f"   loading from: {model_path}")

        # load config and tokenizer locally
        config = AutoConfig.from_pretrained(model_path, local_files_only=True)
        tok = AutoTokenizer.from_pretrained(model_path, local_files_only=True)

        # detect base model type
        model_type = getattr(config, "model_type", "roberta")
        if model_type == "roberta":
            base_model_id = "roberta-base"
        elif model_type == "bert":
            base_model_id = "bert-base-uncased"
        else:
            base_model_id = "roberta-base"

        # load base model first
        base = AutoModelForSequenceClassification.from_pretrained(
            base_model_id,
            num_labels=getattr(config, "num_labels", 2),
            local_files_only=False,  # downloads once if not cached
            ignore_mismatched_sizes=True
        )

        # attach LoRA adapter if present
        adapter_cfg = os.path.join(model_path, "adapter_config.json")
        adapter_weights = os.path.join(model_path, "adapter_model.safetensors")
        if os.path.exists(adapter_cfg) and os.path.exists(adapter_weights):
            print("   applying lora adapter weights...")
            model = PeftModel.from_pretrained(
                base,
                model_path,
                local_files_only=True,
                is_trainable=False
            )
        else:
            print("   no adapter found, using base model only")
            model = base

        model.to(self.device)
        model.eval()
        print("   model loaded fully offline\n")
        return model, tok

    def _load_threshold(self, model_path):
        """Load the tuned threshold value from best_meta.json if available."""
        meta_path = os.path.join(model_path, "best_meta.json")
        if os.path.exists(meta_path):
            try:
                with open(meta_path, "r") as f:
                    data = json.load(f)
                    return float(data.get("chosen_threshold", 0.5))
            except Exception:
                pass
        return 0.5

    # ------------------------------------------------------------

    def _predict(self, text, model, tokenizer, threshold=0.5):
        """Tokenize, infer probabilities, apply tuned threshold, and return 0/1."""
        enc = tokenizer(
            text,
            truncation=True,
            padding=True,
            max_length=256,
            return_tensors="pt"
        ).to(self.device)

        with torch.no_grad():
            logits = model(**enc).logits
            probs = torch.softmax(logits, dim=1).cpu().numpy()[0]

        pred = int(probs[1] >= threshold)
        print(f"text: {text}")
        print(f"probabilities: [not at risk={probs[0]:.4f}, at risk={probs[1]:.4f}]")
        print(f"prediction: {'at risk' if pred == 1 else 'not at risk'} (threshold={threshold:.3f})")
        return pred

    def __call__(self, text):
        """Run safety check on input text using primary (or fallback if fails)."""
        try:
            return self._predict(text, self.primary_model, self.primary_tokenizer, self.primary_threshold)
        except Exception as e:
            print("primary model failed:", e)
            print("switching to fallback model...")
            return self._predict(text, self.fallback_model, self.fallback_tokenizer, self.fallback_threshold)
