# -*- coding: utf-8 -*-
"""phase3_RiskClassifierVariants.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypzGBdSNicEs-zumBF57tLZy63Qk0YYG
"""

pip -q install "transformers>=4.41" "peft>=0.12.0" safetensors

"""# **Ensemble of MentalRoBERTa and MentalBERT**"""

# ============================================================
# RiskClassifier_Ensemble_V4 — averages probabilities of both models
# ============================================================
import os, torch, numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification

class RiskClassifier_Ensemble:
    """
    RiskClassifier_Ensemble(text) → returns both:
        • prediction (0 = not at risk, 1 = at risk)
        • probabilities for each class
    Ensemble of:
      • mental_mental-roberta-base
      • mental_mental-bert-base-uncased
    """

    def __init__(self, base_dir="/content/drive/MyDrive/DSAProjectResults_V4/saved_models"):
        self.base_dir = base_dir
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Model paths
        self.roberta_path = os.path.join(base_dir, "mental_mental-roberta-base")
        self.bert_path    = os.path.join(base_dir, "mental_mental-bert-base-uncased")

        print(f"[RiskClassifier Ensemble] Using base directory: {self.base_dir}")
        self.roberta_model, self.roberta_tok = self._load_model(self.roberta_path)
        self.bert_model, self.bert_tok       = self._load_model(self.bert_path)

    # ------------------------------------------------------------
    def _load_model(self, path):
        if not os.path.exists(path):
            raise FileNotFoundError(f"Model folder not found: {path}")
        tok = AutoTokenizer.from_pretrained(path)
        model = AutoModelForSequenceClassification.from_pretrained(path)
        model.to(self.device).eval()
        print(f"   ✅ Loaded model from {path}")
        return model, tok

    # ------------------------------------------------------------
    def _predict_probs(self, text, model, tokenizer):
        enc = tokenizer(text, truncation=True, padding=True, max_length=256,
                        return_tensors="pt").to(self.device)
        with torch.no_grad():
            logits = model(**enc).logits
            probs = torch.softmax(logits, dim=1).cpu().numpy()[0]
        return probs

    # ------------------------------------------------------------
    def __call__(self, text, threshold=0.5, verbose=True):
        # Get probabilities from both models
        probs_roberta = self._predict_probs(text, self.roberta_model, self.roberta_tok)
        probs_bert    = self._predict_probs(text, self.bert_model, self.bert_tok)

        # Average the "at risk" probabilities
        avg_prob_1 = np.mean([probs_roberta[1], probs_bert[1]])
        avg_prob_0 = 1 - avg_prob_1
        pred = int(avg_prob_1 >= threshold)

        if verbose:
            print(f"\ntext: {text}")
            print(f"roberta → [0={probs_roberta[0]:.4f}, 1={probs_roberta[1]:.4f}]")
            print(f"bert    → [0={probs_bert[0]:.4f}, 1={probs_bert[1]:.4f}]")
            print(f"avg     → [not at risk={avg_prob_0:.4f}, at risk={avg_prob_1:.4f}]")
            print(f"prediction: {'at risk' if pred else 'not at risk'}")

        # ✅ Return both the prediction and probabilities
        return {
            "prediction": pred,
            "probs": {
                "not_at_risk": float(avg_prob_0),
                "at_risk": float(avg_prob_1)
            }
        }

# ============================================================
# DEMO: Run RiskClassifier on 5 sample texts per group
# ============================================================

demo_texts = {
    "anxiety/depression": [
        "I feel like I’m constantly pretending to be okay when inside I’m falling apart. Every morning feels heavier than the last.",
        "My chest feels tight all the time and I can’t stop overthinking everything I say or do. It’s exhausting.",
        "I can’t remember the last time I genuinely felt happy. I’m just tired of existing like this.",
        "Sometimes I wish I could disappear for a while, just to stop feeling this constant pressure in my head.",
        "Even when I’m surrounded by people, I feel like I’m completely alone. It’s like nothing really matters anymore."
    ],
    "colloquial suicide terms": [
        "That presentation was brutal — I nearly died of embarrassment.",
        "This workload is killing me, I swear I haven’t slept in days.",
        "I bombed my exam so badly I could just die right now.",
        "My boss is going to murder me if I’m late again.",
        "That movie was so cringe I wanted to crawl into a hole and disappear."
    ],
    "happy/neutral/sad": [
        "I finally went out for a walk today and it actually felt nice to breathe fresh air.",
        "Spent the whole evening cooking dinner with my family — it was simple but comforting.",
        "Feeling a bit lonely tonight, but I know it’ll pass. Just one of those quiet evenings.",
        "Had a bad day at work, but I treated myself to ice cream afterward, so it’s okay.",
        "I’m nervous about tomorrow’s interview, but also a little excited to see how it goes."
    ],
    "loved ones death": [
        "I still catch myself picking up the phone to call her, then remember she’s gone. The silence hurts the most.",
        "My dad passed away last month and I still can’t bring myself to go through his things. Everything reminds me of him.",
        "Losing my best friend felt like losing a part of myself. I don’t know how to move forward.",
        "It’s been a year since my husband died, but the pain hasn’t faded. I miss his laugh every single day.",
        "I thought grief would get easier with time, but some days it feels like it just started all over again."
    ],
    "suicidal intent": [
        "I’ve already written my goodbye letter. I just don’t see the point of continuing anymore.",
        "Tonight might be the night I finally end it. I’m so tired of hurting all the time.",
        "I’ve made peace with the idea of dying — it actually feels like relief.",
        "I can’t keep doing this; I’ve planned everything out and I’m ready to go.",
        "No one will even notice when I’m gone, and maybe that’s for the best."
    ],
    "suicide topic": [
        "I’ve been reading about assisted suicide laws, and I can see both sides of the argument.",
        "Some people believe choosing to die with dignity should be a human right. I’m still not sure what I think.",
        "The ethics of suicide are complicated — when is it compassion, and when is it giving up?",
        "I watched a documentary about end-of-life decisions, and it really made me question what living well means.",
        "It’s hard to judge someone’s choice to die when we can’t fully understand their pain or perspective."
    ],
    "suicidal but no intent": [
        "I don’t want to live anymore, but I don’t think I could actually go through with ending my life.",
        "Sometimes I just wish I could sleep forever so I wouldn’t have to deal with any of this.",
        "I keep thinking about dying, but then I imagine how my family would feel and I stop.",
        "I don’t have a plan or anything — I just feel like I wouldn’t mind if I didn’t wake up tomorrow.",
        "I’m not in danger right now, but the thought of disappearing feels comforting sometimes."
    ],

    "explicit suicide intent": [
        "goodbye world, i ate a bottle of pills.",
        "im gonna hnag myself later tonight",
        "im going to jump off a bridge, to all the people here thank you but i really cant take it anymore",
        "in my car with carbon monoxide, anytime now, cant wait to die a peaceful death and leave it all behind",
        "help me tell my mother, im sorry i cant continuing living like this, and hope to see her in heaven agn."
    ]
}

# ============================================================
# RUN ALL TEXTS THROUGH YOUR RiskClassifier MODEL
# ============================================================
sc = RiskClassifier_Ensemble()  # make sure your RiskClassifier class is already defined/imported

for group, texts in demo_texts.items():
    print("="*70)
    print(f"GROUP: {group.upper()}")
    print("="*70)
    for t in texts:
        try:
            result = sc(t)
            print(f"→ Predicted: {result}\n")
        except Exception as e:
            print(f"Error on text: {e}\n")

import os, torch, pandas as pd, numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score, confusion_matrix,
    classification_report, roc_curve, precision_recall_curve
)
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# CONFIGURATION
# ============================================================
MODEL_CHOICE = "ensemble"  # choose from: "ensemble", "roberta", "bert"

# Directories
BASE_DIR = "/content/drive/MyDrive/DSAProjectResults_V4"
DATA_PATH = os.path.join(BASE_DIR, "datasets", "risk_test.csv")
SAVE_BASE = os.path.join(BASE_DIR, "phase3")

# Dynamic folder naming
model_names = {
    "ensemble": "RiskClassifier_ensemble",
    "roberta": "RiskClassifier_mentalroberta",
    "bert": "RiskClassifier_mentalbert"
}
SAVE_DIR = os.path.join(SAVE_BASE, model_names[MODEL_CHOICE])
os.makedirs(SAVE_DIR, exist_ok=True)

# ============================================================
# LOAD MODEL
# ============================================================
if MODEL_CHOICE == "ensemble":
    model = RiskClassifier_Ensemble()
    model_name_display = "RiskClassifier Ensemble"
elif MODEL_CHOICE == "roberta":
    model = RiskClassifier_MentalRoBERTa()
    model_name_display = "RiskClassifier MentalRoBERTa"
elif MODEL_CHOICE == "bert":
    model = RiskClassifier_MentalBERT()
    model_name_display = "RiskClassifier MentalBERT"
else:
    raise ValueError("Invalid MODEL_CHOICE. Use 'ensemble', 'roberta', or 'bert'.")

# ============================================================
# LOAD DATA
# ============================================================
test_df = pd.read_csv(DATA_PATH)
texts = test_df["text"].tolist()
labels = test_df["label"].tolist()

# ============================================================
# RUN PREDICTIONS
# ============================================================
preds, probs = [], []
for t in texts:
    with torch.no_grad():
        result = model(t, verbose=False)
        # Handle both dictionary-based and numeric-only returns
        if isinstance(result, dict):
            preds.append(result["prediction"])
            probs.append(result["probs"]["at_risk"])
        else:
            preds.append(result)
            probs.append(0.0)

# ============================================================
# METRICS
# ============================================================
acc  = accuracy_score(labels, preds)
prec = precision_score(labels, preds)
rec  = recall_score(labels, preds)
f1   = f1_score(labels, preds, average="macro")
auc  = roc_auc_score(labels, probs)
ap   = average_precision_score(labels, probs)
cm   = confusion_matrix(labels, preds)
report = classification_report(labels, preds, digits=4)

# ============================================================
# PRINT SUMMARY
# ============================================================
print(f"\n=== {model_name_display.upper()} EVALUATION ===")
print(f"Accuracy      : {acc:.4f}")
print(f"Precision     : {prec:.4f}")
print(f"Recall        : {rec:.4f}")
print(f"Macro F1      : {f1:.4f}")
print(f"ROC-AUC       : {auc:.4f}")
print(f"PR-AUC (AP)   : {ap:.4f}")
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", report)

# ============================================================
# SAVE METRICS + REPORT
# ============================================================
metrics_df = pd.DataFrame([{
    "Model": model_name_display,
    "Accuracy": acc, "Precision": prec, "Recall": rec,
    "Macro_F1": f1, "ROC_AUC": auc, "PR_AUC": ap
}])
metrics_path = os.path.join(SAVE_DIR, "metrics.csv")
metrics_df.to_csv(metrics_path, index=False)

with open(os.path.join(SAVE_DIR, "classification_report.txt"), "w") as f:
    f.write(report)

# Save predictions
pred_df = pd.DataFrame({
    "text": texts,
    "true_label": labels,
    "pred_label": preds,
    "prob_at_risk": probs
})
pred_path = os.path.join(SAVE_DIR, "predictions.csv")
pred_df.to_csv(pred_path, index=False)

# ============================================================
# PLOTS
# ============================================================
# Confusion Matrix
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False)
plt.xlabel("Predicted"); plt.ylabel("True")
plt.title(f"{model_name_display} — Confusion Matrix")
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "confusion_matrix.png"), dpi=300)
plt.close()

# ROC Curve
fpr, tpr, _ = roc_curve(labels, probs)
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"ROC-AUC = {auc:.3f}")
plt.plot([0,1],[0,1],'k--',alpha=0.5)
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve — {model_name_display}")
plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "roc_curve.png"), dpi=300)
plt.close()

# PR Curve
prec_curve, rec_curve, _ = precision_recall_curve(labels, probs)
plt.figure(figsize=(6,5))
plt.plot(rec_curve, prec_curve, label=f"PR-AUC = {ap:.3f}")
plt.xlabel("Recall"); plt.ylabel("Precision")
plt.title(f"Precision–Recall Curve — {model_name_display}")
plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "pr_curve.png"), dpi=300)
plt.close()

# ============================================================
# SUMMARY OUTPUT
# ============================================================
print(f"\n✅ All evaluation outputs saved to:\n{SAVE_DIR}")
print(f"├─ metrics.csv")
print(f"├─ classification_report.txt")
print(f"├─ predictions.csv")
print(f"├─ confusion_matrix.png")
print(f"├─ roc_curve.png")
print(f"└─ pr_curve.png\n")

"""# **MentalRoBERTa only version**"""

# ============================================================
# RiskClassifier_MentalRoBERTa
# ============================================================
import os, torch, numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification

class RiskClassifier_MentalRoBERTa:
    """
    RiskClassifier_MentalRoBERTa(text) → returns:
        • prediction (0 = not at risk, 1 = at risk)
        • probabilities for each class

    Loads the fine-tuned MentalRoBERTa model from saved_models/.
    """

    def __init__(self, base_dir="/content/drive/MyDrive/DSAProjectResults_V4/saved_models"):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model_path = os.path.join(base_dir, "mental_mental-roberta-base")

        print(f"[RiskClassifier_MentalRoBERTa] Loading model from {self.model_path}")
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_path)
        self.model = AutoModelForSequenceClassification.from_pretrained(self.model_path)
        self.model.to(self.device).eval()
        print("✅ MentalRoBERTa loaded successfully\n")

    # ------------------------------------------------------------
    def __call__(self, text, threshold=0.5, verbose=True):
        enc = self.tokenizer(text, truncation=True, padding=True, max_length=256,
                             return_tensors="pt").to(self.device)
        with torch.no_grad():
            logits = self.model(**enc).logits
            probs = torch.softmax(logits, dim=1).cpu().numpy()[0]

        pred = int(probs[1] >= threshold)

        if verbose:
            print(f"\ntext: {text}")
            print(f"probabilities: [not at risk={probs[0]:.4f}, at risk={probs[1]:.4f}]")
            print(f"prediction: {'at risk' if pred else 'not at risk'}")

        # ✅ Return both the prediction and probabilities
        return {
            "prediction": pred,
            "probs": {
                "not_at_risk": float(probs[0]),
                "at_risk": float(probs[1])
            }
        }

# ============================================================
# DEMO: Run RiskClassifier on 5 sample texts per group
# ============================================================

demo_texts = {
    "anxiety/depression": [
        "I feel like I’m constantly pretending to be okay when inside I’m falling apart. Every morning feels heavier than the last.",
        "My chest feels tight all the time and I can’t stop overthinking everything I say or do. It’s exhausting.",
        "I can’t remember the last time I genuinely felt happy. I’m just tired of existing like this.",
        "Sometimes I wish I could disappear for a while, just to stop feeling this constant pressure in my head.",
        "Even when I’m surrounded by people, I feel like I’m completely alone. It’s like nothing really matters anymore."
    ],
    "colloquial suicide terms": [
        "That presentation was brutal — I nearly died of embarrassment.",
        "This workload is killing me, I swear I haven’t slept in days.",
        "I bombed my exam so badly I could just die right now.",
        "My boss is going to murder me if I’m late again.",
        "That movie was so cringe I wanted to crawl into a hole and disappear."
    ],
    "happy/neutral/sad": [
        "I finally went out for a walk today and it actually felt nice to breathe fresh air.",
        "Spent the whole evening cooking dinner with my family — it was simple but comforting.",
        "Feeling a bit lonely tonight, but I know it’ll pass. Just one of those quiet evenings.",
        "Had a bad day at work, but I treated myself to ice cream afterward, so it’s okay.",
        "I’m nervous about tomorrow’s interview, but also a little excited to see how it goes."
    ],
    "loved ones death": [
        "My best friend killed herself.",
        "I still catch myself picking up the phone to call her, then remember she’s gone. The silence hurts the most.",
        "My dad passed away last month and I still can’t bring myself to go through his things. Everything reminds me of him.",
        "Losing my best friend felt like losing a part of myself. I don’t know how to move forward.",
        "It’s been a year since my husband died, but the pain hasn’t faded. I miss his laugh every single day.",
        "I thought grief would get easier with time, but some days it feels like it just started all over again."
    ],
    "suicidal intent": [
        "I’ve already written my goodbye letter. I just don’t see the point of continuing anymore.",
        "Tonight might be the night I finally end it. I’m so tired of hurting all the time.",
        "I’ve made peace with the idea of dying — it actually feels like relief.",
        "I can’t keep doing this; I’ve planned everything out and I’m ready to go.",
        "No one will even notice when I’m gone, and maybe that’s for the best."
    ],
    "suicide topic": [
        "I’ve been reading about assisted suicide laws, and I can see both sides of the argument.",
        "Some people believe choosing to die with dignity should be a human right. I’m still not sure what I think.",
        "The ethics of suicide are complicated — when is it compassion, and when is it giving up?",
        "I watched a documentary about end-of-life decisions, and it really made me question what living well means.",
        "It’s hard to judge someone’s choice to die when we can’t fully understand their pain or perspective."
    ],
    "suicidal but no intent": [
        "I don’t want to live anymore, but I don’t think I could actually go through with ending my life.",
        "Sometimes I just wish I could sleep forever so I wouldn’t have to deal with any of this.",
        "I keep thinking about dying, but then I imagine how my family would feel and I stop.",
        "I don’t have a plan or anything — I just feel like I wouldn’t mind if I didn’t wake up tomorrow.",
        "I’m not in danger right now, but the thought of disappearing feels comforting sometimes."
    ],

    "explicit suicide intent": [
        "goodbye world, i ate a bottle of pills.",
        "im gonna hnag myself later tonight",
        "im going to jump off a bridge, to all the people here thank you but i really cant take it anymore",
        "in my car with carbon monoxide, anytime now, cant wait to die a peaceful death and leave it all behind",
        "help me tell my mother, im sorry i cant continuing living like this, and hope to see her in heaven agn."
    ]
}

# ============================================================
# RUN ALL TEXTS THROUGH YOUR RiskClassifier MODEL
# ============================================================
sc = RiskClassifier_MentalRoBERTa()  # make sure your RiskClassifier class is already defined/imported

for group, texts in demo_texts.items():
    print("="*70)
    print(f"GROUP: {group.upper()}")
    print("="*70)
    for t in texts:
        try:
            result = sc(t)
            print(f"→ Predicted: {result}\n")
        except Exception as e:
            print(f"Error on text: {e}\n")

import os, torch, pandas as pd, numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score, confusion_matrix,
    classification_report, roc_curve, precision_recall_curve
)
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# CONFIGURATION
# ============================================================
MODEL_CHOICE = "roberta"  # choose from: "ensemble", "roberta", "bert"

# Directories
BASE_DIR = "/content/drive/MyDrive/DSAProjectResults_V4"
DATA_PATH = os.path.join(BASE_DIR, "datasets", "risk_test.csv")
SAVE_BASE = os.path.join(BASE_DIR, "phase3")

# Dynamic folder naming
model_names = {
    "ensemble": "RiskClassifier_ensemble",
    "roberta": "RiskClassifier_mentalroberta",
    "bert": "RiskClassifier_mentalbert"
}
SAVE_DIR = os.path.join(SAVE_BASE, model_names[MODEL_CHOICE])
os.makedirs(SAVE_DIR, exist_ok=True)

# ============================================================
# LOAD MODEL
# ============================================================
if MODEL_CHOICE == "ensemble":
    model = RiskClassifier_Ensemble()
    model_name_display = "RiskClassifier Ensemble"
elif MODEL_CHOICE == "roberta":
    model = RiskClassifier_MentalRoBERTa()
    model_name_display = "RiskClassifier MentalRoBERTa"
elif MODEL_CHOICE == "bert":
    model = RiskClassifier_MentalBERT()
    model_name_display = "RiskClassifier MentalBERT"
else:
    raise ValueError("Invalid MODEL_CHOICE. Use 'ensemble', 'roberta', or 'bert'.")

# ============================================================
# LOAD DATA
# ============================================================
test_df = pd.read_csv(DATA_PATH)
texts = test_df["text"].tolist()
labels = test_df["label"].tolist()

# ============================================================
# RUN PREDICTIONS
# ============================================================
preds, probs = [], []
for t in texts:
    with torch.no_grad():
        result = model(t, verbose=False)
        # Handle both dictionary-based and numeric-only returns
        if isinstance(result, dict):
            preds.append(result["prediction"])
            probs.append(result["probs"]["at_risk"])
        else:
            preds.append(result)
            probs.append(0.0)

# ============================================================
# METRICS
# ============================================================
acc  = accuracy_score(labels, preds)
prec = precision_score(labels, preds)
rec  = recall_score(labels, preds)
f1   = f1_score(labels, preds, average="macro")
auc  = roc_auc_score(labels, probs)
ap   = average_precision_score(labels, probs)
cm   = confusion_matrix(labels, preds)
report = classification_report(labels, preds, digits=4)

# ============================================================
# PRINT SUMMARY
# ============================================================
print(f"\n=== {model_name_display.upper()} EVALUATION ===")
print(f"Accuracy      : {acc:.4f}")
print(f"Precision     : {prec:.4f}")
print(f"Recall        : {rec:.4f}")
print(f"Macro F1      : {f1:.4f}")
print(f"ROC-AUC       : {auc:.4f}")
print(f"PR-AUC (AP)   : {ap:.4f}")
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", report)

# ============================================================
# SAVE METRICS + REPORT
# ============================================================
metrics_df = pd.DataFrame([{
    "Model": model_name_display,
    "Accuracy": acc, "Precision": prec, "Recall": rec,
    "Macro_F1": f1, "ROC_AUC": auc, "PR_AUC": ap
}])
metrics_path = os.path.join(SAVE_DIR, "metrics.csv")
metrics_df.to_csv(metrics_path, index=False)

with open(os.path.join(SAVE_DIR, "classification_report.txt"), "w") as f:
    f.write(report)

# Save predictions
pred_df = pd.DataFrame({
    "text": texts,
    "true_label": labels,
    "pred_label": preds,
    "prob_at_risk": probs
})
pred_path = os.path.join(SAVE_DIR, "predictions.csv")
pred_df.to_csv(pred_path, index=False)

# ============================================================
# PLOTS
# ============================================================
# Confusion Matrix
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False)
plt.xlabel("Predicted"); plt.ylabel("True")
plt.title(f"{model_name_display} — Confusion Matrix")
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "confusion_matrix.png"), dpi=300)
plt.close()

# ROC Curve
fpr, tpr, _ = roc_curve(labels, probs)
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"ROC-AUC = {auc:.3f}")
plt.plot([0,1],[0,1],'k--',alpha=0.5)
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve — {model_name_display}")
plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "roc_curve.png"), dpi=300)
plt.close()

# PR Curve
prec_curve, rec_curve, _ = precision_recall_curve(labels, probs)
plt.figure(figsize=(6,5))
plt.plot(rec_curve, prec_curve, label=f"PR-AUC = {ap:.3f}")
plt.xlabel("Recall"); plt.ylabel("Precision")
plt.title(f"Precision–Recall Curve — {model_name_display}")
plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "pr_curve.png"), dpi=300)
plt.close()

# ============================================================
# SUMMARY OUTPUT
# ============================================================
print(f"\n✅ All evaluation outputs saved to:\n{SAVE_DIR}")
print(f"├─ metrics.csv")
print(f"├─ classification_report.txt")
print(f"├─ predictions.csv")
print(f"├─ confusion_matrix.png")
print(f"├─ roc_curve.png")
print(f"└─ pr_curve.png\n")

"""# **BERT only version**"""

# ============================================================
# RiskClassifier_MentalBERT
# ============================================================
import os, torch, numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification

class RiskClassifier_MentalBERT:
    """
    RiskClassifier_MentalBERT(text) → returns:
        • prediction (0 = not at risk, 1 = at risk)
        • probabilities for each class

    Loads the fine-tuned MentalBERT model from saved_models/.
    """

    def __init__(self, base_dir="/content/drive/MyDrive/DSAProjectResults_V4/saved_models"):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model_path = os.path.join(base_dir, "mental_mental-bert-base-uncased")

        print(f"[RiskClassifier_MentalBERT] Loading model from {self.model_path}")
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_path)
        self.model = AutoModelForSequenceClassification.from_pretrained(self.model_path)
        self.model.to(self.device).eval()
        print("✅ MentalBERT loaded successfully\n")

    # ------------------------------------------------------------
    def __call__(self, text, threshold=0.5, verbose=True):
        enc = self.tokenizer(text, truncation=True, padding=True, max_length=256,
                             return_tensors="pt").to(self.device)
        with torch.no_grad():
            logits = self.model(**enc).logits
            probs = torch.softmax(logits, dim=1).cpu().numpy()[0]

        pred = int(probs[1] >= threshold)

        if verbose:
            print(f"\ntext: {text}")
            print(f"probabilities: [not at risk={probs[0]:.4f}, at risk={probs[1]:.4f}]")
            print(f"prediction: {'at risk' if pred else 'not at risk'}")

        # ✅ Return both the prediction and probabilities
        return {
            "prediction": pred,
            "probs": {
                "not_at_risk": float(probs[0]),
                "at_risk": float(probs[1])
            }
        }

# ============================================================
# DEMO: Run RiskClassifier on 5 sample texts per group
# ============================================================

demo_texts = {
    "anxiety/depression": [
        "I feel like I’m constantly pretending to be okay when inside I’m falling apart. Every morning feels heavier than the last.",
        "My chest feels tight all the time and I can’t stop overthinking everything I say or do. It’s exhausting.",
        "I can’t remember the last time I genuinely felt happy. I’m just tired of existing like this.",
        "Sometimes I wish I could disappear for a while, just to stop feeling this constant pressure in my head.",
        "Even when I’m surrounded by people, I feel like I’m completely alone. It’s like nothing really matters anymore."
    ],
    "colloquial suicide terms": [
        "That presentation was brutal — I nearly died of embarrassment.",
        "This workload is killing me, I swear I haven’t slept in days.",
        "I bombed my exam so badly I could just die right now.",
        "My boss is going to murder me if I’m late again.",
        "That movie was so cringe I wanted to crawl into a hole and disappear."
    ],
    "happy/neutral/sad": [
        "I finally went out for a walk today and it actually felt nice to breathe fresh air.",
        "Spent the whole evening cooking dinner with my family — it was simple but comforting.",
        "Feeling a bit lonely tonight, but I know it’ll pass. Just one of those quiet evenings.",
        "Had a bad day at work, but I treated myself to ice cream afterward, so it’s okay.",
        "I’m nervous about tomorrow’s interview, but also a little excited to see how it goes."
    ],
    "loved ones death": [
        "My best friend killed herself.",
        "I still catch myself picking up the phone to call her, then remember she’s gone. The silence hurts the most.",
        "My dad passed away last month and I still can’t bring myself to go through his things. Everything reminds me of him.",
        "Losing my best friend felt like losing a part of myself. I don’t know how to move forward.",
        "It’s been a year since my husband died, but the pain hasn’t faded. I miss his laugh every single day.",
        "I thought grief would get easier with time, but some days it feels like it just started all over again."
    ],
    "suicidal intent": [
        "I’ve already written my goodbye letter. I just don’t see the point of continuing anymore.",
        "Tonight might be the night I finally end it. I’m so tired of hurting all the time.",
        "I’ve made peace with the idea of dying — it actually feels like relief.",
        "I can’t keep doing this; I’ve planned everything out and I’m ready to go.",
        "No one will even notice when I’m gone, and maybe that’s for the best."
    ],
    "suicide topic": [
        "I’ve been reading about assisted suicide laws, and I can see both sides of the argument.",
        "Some people believe choosing to die with dignity should be a human right. I’m still not sure what I think.",
        "The ethics of suicide are complicated — when is it compassion, and when is it giving up?",
        "I watched a documentary about end-of-life decisions, and it really made me question what living well means.",
        "It’s hard to judge someone’s choice to die when we can’t fully understand their pain or perspective."
    ],
    "suicidal but no intent": [
        "I don’t want to live anymore, but I don’t think I could actually go through with ending my life.",
        "Sometimes I just wish I could sleep forever so I wouldn’t have to deal with any of this.",
        "I keep thinking about dying, but then I imagine how my family would feel and I stop.",
        "I don’t have a plan or anything — I just feel like I wouldn’t mind if I didn’t wake up tomorrow.",
        "I’m not in danger right now, but the thought of disappearing feels comforting sometimes."
    ],

    "explicit suicide intent": [
        "goodbye world, i ate a bottle of pills.",
        "im gonna hnag myself later tonight",
        "im going to jump off a bridge, to all the people here thank you but i really cant take it anymore",
        "in my car with carbon monoxide, anytime now, cant wait to die a peaceful death and leave it all behind",
        "help me tell my mother, im sorry i cant continuing living like this, and hope to see her in heaven agn."
    ]
}

# ============================================================
# RUN ALL TEXTS THROUGH YOUR RiskClassifier MODEL
# ============================================================
sc = RiskClassifier_MentalBERT()  # make sure your RiskClassifier class is already defined/imported

for group, texts in demo_texts.items():
    print("="*70)
    print(f"GROUP: {group.upper()}")
    print("="*70)
    for t in texts:
        try:
            result = sc(t)
            print(f"→ Predicted: {result}\n")
        except Exception as e:
            print(f"Error on text: {e}\n")

import os, torch, pandas as pd, numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score, confusion_matrix,
    classification_report, roc_curve, precision_recall_curve
)
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================
# CONFIGURATION
# ============================================================
MODEL_CHOICE = "bert"  # choose from: "ensemble", "roberta", "bert"

# Directories
BASE_DIR = "/content/drive/MyDrive/DSAProjectResults_V4"
DATA_PATH = os.path.join(BASE_DIR, "datasets", "risk_test.csv")
SAVE_BASE = os.path.join(BASE_DIR, "phase3")

# Dynamic folder naming
model_names = {
    "ensemble": "RiskClassifier_ensemble",
    "roberta": "RiskClassifier_mentalroberta",
    "bert": "RiskClassifier_mentalbert"
}
SAVE_DIR = os.path.join(SAVE_BASE, model_names[MODEL_CHOICE])
os.makedirs(SAVE_DIR, exist_ok=True)

# ============================================================
# LOAD MODEL
# ============================================================
if MODEL_CHOICE == "ensemble":
    model = RiskClassifier_Ensemble()
    model_name_display = "RiskClassifier Ensemble"
elif MODEL_CHOICE == "roberta":
    model = RiskClassifier_MentalRoBERTa()
    model_name_display = "RiskClassifier MentalRoBERTa"
elif MODEL_CHOICE == "bert":
    model = RiskClassifier_MentalBERT()
    model_name_display = "RiskClassifier MentalBERT"
else:
    raise ValueError("Invalid MODEL_CHOICE. Use 'ensemble', 'roberta', or 'bert'.")

# ============================================================
# LOAD DATA
# ============================================================
test_df = pd.read_csv(DATA_PATH)
texts = test_df["text"].tolist()
labels = test_df["label"].tolist()

# ============================================================
# RUN PREDICTIONS
# ============================================================
preds, probs = [], []
for t in texts:
    with torch.no_grad():
        result = model(t, verbose=False)
        # Handle both dictionary-based and numeric-only returns
        if isinstance(result, dict):
            preds.append(result["prediction"])
            probs.append(result["probs"]["at_risk"])
        else:
            preds.append(result)
            probs.append(0.0)

# ============================================================
# METRICS
# ============================================================
acc  = accuracy_score(labels, preds)
prec = precision_score(labels, preds)
rec  = recall_score(labels, preds)
f1   = f1_score(labels, preds, average="macro")
auc  = roc_auc_score(labels, probs)
ap   = average_precision_score(labels, probs)
cm   = confusion_matrix(labels, preds)
report = classification_report(labels, preds, digits=4)

# ============================================================
# PRINT SUMMARY
# ============================================================
print(f"\n=== {model_name_display.upper()} EVALUATION ===")
print(f"Accuracy      : {acc:.4f}")
print(f"Precision     : {prec:.4f}")
print(f"Recall        : {rec:.4f}")
print(f"Macro F1      : {f1:.4f}")
print(f"ROC-AUC       : {auc:.4f}")
print(f"PR-AUC (AP)   : {ap:.4f}")
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", report)

# ============================================================
# SAVE METRICS + REPORT
# ============================================================
metrics_df = pd.DataFrame([{
    "Model": model_name_display,
    "Accuracy": acc, "Precision": prec, "Recall": rec,
    "Macro_F1": f1, "ROC_AUC": auc, "PR_AUC": ap
}])
metrics_path = os.path.join(SAVE_DIR, "metrics.csv")
metrics_df.to_csv(metrics_path, index=False)

with open(os.path.join(SAVE_DIR, "classification_report.txt"), "w") as f:
    f.write(report)

# Save predictions
pred_df = pd.DataFrame({
    "text": texts,
    "true_label": labels,
    "pred_label": preds,
    "prob_at_risk": probs
})
pred_path = os.path.join(SAVE_DIR, "predictions.csv")
pred_df.to_csv(pred_path, index=False)

# ============================================================
# PLOTS
# ============================================================
# Confusion Matrix
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False)
plt.xlabel("Predicted"); plt.ylabel("True")
plt.title(f"{model_name_display} — Confusion Matrix")
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "confusion_matrix.png"), dpi=300)
plt.close()

# ROC Curve
fpr, tpr, _ = roc_curve(labels, probs)
plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"ROC-AUC = {auc:.3f}")
plt.plot([0,1],[0,1],'k--',alpha=0.5)
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve — {model_name_display}")
plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "roc_curve.png"), dpi=300)
plt.close()

# PR Curve
prec_curve, rec_curve, _ = precision_recall_curve(labels, probs)
plt.figure(figsize=(6,5))
plt.plot(rec_curve, prec_curve, label=f"PR-AUC = {ap:.3f}")
plt.xlabel("Recall"); plt.ylabel("Precision")
plt.title(f"Precision–Recall Curve — {model_name_display}")
plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, "pr_curve.png"), dpi=300)
plt.close()

# ============================================================
# SUMMARY OUTPUT
# ============================================================
print(f"\n✅ All evaluation outputs saved to:\n{SAVE_DIR}")
print(f"├─ metrics.csv")
print(f"├─ classification_report.txt")
print(f"├─ predictions.csv")
print(f"├─ confusion_matrix.png")
print(f"├─ roc_curve.png")
print(f"└─ pr_curve.png\n")

"""# **Summary Overlay Plots**"""

# ============================================================
# OVERLAY ROC-AUC & PR-AUC PLOTS — Phase 3 RiskClassifier Variants
# ============================================================
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, precision_recall_curve, auc, average_precision_score

# ------------------------------------------------------------
# Directories
# ------------------------------------------------------------
BASE_DIR = "/content/drive/MyDrive/DSAProjectResults_V4/phase3"
SAVE_DIR = os.path.join(BASE_DIR, "comparison_overlay")
os.makedirs(SAVE_DIR, exist_ok=True)

# ------------------------------------------------------------
# Model variants and their paths
# ------------------------------------------------------------
models = {
    "RiskClassifier_MentalRoBERTa": os.path.join(BASE_DIR, "RiskClassifier_mentalroberta"),
    "RiskClassifier_MentalBERT": os.path.join(BASE_DIR, "RiskClassifier_mentalbert"),
    "RiskClassifier_Ensemble": os.path.join(BASE_DIR, "RiskClassifier_ensemble")
}

# ------------------------------------------------------------
# Load predictions for each model
# ------------------------------------------------------------
data, summary = {}, []
for name, path in models.items():
    csv_path = os.path.join(path, "predictions.csv")
    if not os.path.exists(csv_path):
        print(f"⚠️ Missing predictions.csv for {name}, skipping...")
        continue

    df = pd.read_csv(csv_path)
    if "true_label" not in df or "prob_at_risk" not in df:
        print(f"⚠️ Invalid file format for {name}, skipping...")
        continue

    y_true = df["true_label"].values
    y_prob = df["prob_at_risk"].values
    data[name] = (y_true, y_prob)

    # compute metrics for summary
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    auc_val = auc(fpr, tpr)
    ap_val = average_precision_score(y_true, y_prob)
    summary.append({"Model": name, "ROC_AUC": auc_val, "PR_AUC": ap_val})

    print(f"✅ Loaded {len(df)} samples for {name}")

# ------------------------------------------------------------
# Overlay ROC Curve
# ------------------------------------------------------------
plt.figure(figsize=(7,6))
for name, (y_true, y_prob) in data.items():
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    auc_val = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC={auc_val:.3f})")

plt.plot([0,1],[0,1],'k--',alpha=0.5)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Overlay ROC Curves — RiskClassifier Variants")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
roc_path = os.path.join(SAVE_DIR, "overlay_roc_curve.png")
plt.savefig(roc_path, dpi=300)
plt.close()

# ------------------------------------------------------------
# Overlay PR Curve
# ------------------------------------------------------------
plt.figure(figsize=(7,6))
for name, (y_true, y_prob) in data.items():
    prec, rec, _ = precision_recall_curve(y_true, y_prob)
    ap_val = average_precision_score(y_true, y_prob)
    plt.plot(rec, prec, label=f"{name} (AP={ap_val:.3f})")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Overlay Precision–Recall Curves — RiskClassifier Variants")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
pr_path = os.path.join(SAVE_DIR, "overlay_pr_curve.png")
plt.savefig(pr_path, dpi=300)
plt.close()

# ------------------------------------------------------------
# Summary Table
# ------------------------------------------------------------
summary_df = pd.DataFrame(summary).sort_values(by="ROC_AUC", ascending=False).reset_index(drop=True)
summary_path = os.path.join(SAVE_DIR, "overlay_auc_summary.csv")
summary_df.to_csv(summary_path, index=False)

print("\n✅ Overlay plots + summary saved successfully!")
print(f"├─ ROC overlay → {roc_path}")
print(f"├─ PR overlay  → {pr_path}")
print(f"└─ Summary CSV → {summary_path}\n")
print(summary_df)

