# -*- coding: utf-8 -*-
"""safetycheckmodels_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bE3qrwAMCf5okEf59UTWMNHL5_C0IVDU

# **Utils**
"""

# installs
!pip -q install transformers datasets peft accelerate scikit-learn torch matplotlib joblib
!pip -q install nlpaug

from huggingface_hub import login
login() 

# imports
import os, gc, json, random, warnings
from pathlib import Path
from itertools import product

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm

import torch
from datasets import load_dataset, Dataset
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, average_precision_score, confusion_matrix,
    roc_curve, precision_recall_curve, auc, classification_report
)

from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    TrainingArguments, Trainer
)
from peft import LoraConfig, get_peft_model, TaskType

import nlpaug.augmenter.word as naw
import joblib
from google.colab import drive

# CuBLAS reproducibility
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":16:8"

# Disable TensorFloat32 (ensures exact matmul determinism on Ampere GPUs)
os.environ["NVIDIA_TF32_OVERRIDE"] = "0"
os.environ["TORCH_CUDNN_V8_API_DISABLED"] = "1"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

# env + warnings
warnings.filterwarnings("ignore")
os.environ["WANDB_DISABLED"] = "true"
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "1"

# device + seeds
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("using device:", device)

# reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.set_deterministic_debug_mode("warn")
print(f"Deterministic mode ON with seed {SEED}")

# mount drive and directories
drive.mount('/content/drive')

BASE_DIR   = Path("/content/drive/MyDrive/DSAProjectResults_V4")
DATA_DIR   = BASE_DIR / "datasets"
PHASE2_DIR   = BASE_DIR / "phase2"
MODELS_DIR = BASE_DIR / "saved_models"

for d in [BASE_DIR, DATA_DIR, MODELS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

print(f"All directories ready under: {BASE_DIR}")

"""# **Dataset EDA, Clean and Preprocessing**

### **Load new risk dataset**
Dataset was scrapped from different subreddits to provide more variety of type of suicide texts
"""

# load dataset
df = pd.read_csv("/content/drive/MyDrive/DSAProjectResults_V4/datasets/new_risk_data.csv")
TEXT_COL, LABEL_COL = "text", "label"
X, y = df[TEXT_COL].tolist(), df[LABEL_COL].tolist()
num_labels = len(set(y))
df.head(10)

print(df.shape)

print("Label counts:")
print(df["label"].value_counts())

"""### **Load hugging face suicide dataset**
Concat hugging face data (non-empty and labelled 1) to our new_risk_data.csv, also removed dumplicated text, check if combined dataset is balanced
"""

# Load your dataset
print("Your dataset columns:", df.columns.tolist())

# Load HF dataset (train + test)
hf_ds = load_dataset("jingjietan/sdcnl-suicide")
hf_train = hf_ds["train"].to_pandas()
hf_test = hf_ds["test"].to_pandas()

# Combine and clean
hf_df = pd.concat([hf_train, hf_test], ignore_index=True)
hf_df = hf_df.drop(columns=["__index_level_0__"], errors="ignore")  # drop index column if present

# Rename to match your format
hf_df = hf_df.rename(columns={
    "selftext": "text",
    "is_suicide": "label"
})

# Keep only suicidal intent (label == 1)
hf_df = hf_df[hf_df["label"] == 1].copy()

# Remove 'emptypost', null, or whitespace-only texts
hf_df["text"] = hf_df["text"].astype(str)
hf_df = hf_df[~hf_df["text"].str.lower().eq("emptypost")]  # remove 'emptypost'
hf_df = hf_df[hf_df["text"].str.strip().ne("")]  # remove empty or whitespace-only
print(f"HF suicidal-intent samples kept (non-empty): {len(hf_df)}")

# Add missing columns
hf_df["source"] = "jingjietan/sdcnl-suicide"
hf_df["group"] = "suicidal intent"
hf_df["len(words)"] = hf_df["text"].fillna("").apply(lambda x: len(x.split()))

# Reorder to match your dataset’s column order
hf_df = hf_df[df.columns]

# Concatenate
combined_df = pd.concat([df, hf_df], ignore_index=True)
print("concat hf_df and df")

# Remove duplicates (based on text)
dup_mask = combined_df.duplicated(subset=["text"], keep=False)
dup_count = dup_mask.sum()
combined_df = combined_df.drop_duplicates(subset=["text"], keep="first").reset_index(drop=True)
print(f"Removed {dup_count} duplicate rows (based on 'text').")

print("\nCombined dataset created!")
print("Shape:", combined_df.shape)
print("Columns:", combined_df.columns.tolist())

# Quick checks
print("\nLabel distribution (%):")
print((combined_df["label"].value_counts(normalize=True) * 100).round(2))

print("\nLabel Counts:")
print(combined_df["label"].value_counts())

print("\nGroup distribution (%):")
print((combined_df["group"].value_counts(normalize=True) * 100).round(2))

print("\nGroup counts:")
print(combined_df["group"].value_counts())

print("\nSources:")
print(combined_df["source"].value_counts())

"""### **Balancing Combined Dataset**
As dataset was imbalanced and label 1 was the minority, undersampled label 0 across different groups, final risk_dataset_cleaned.csv is balanced
"""

# =======================================================
# STEP — DOWNSAMPLE LABEL 0 TO MATCH LABEL 1
# =======================================================
SEED = 42

df0 = combined_df[combined_df["label"] == 0].copy()
df1 = combined_df[combined_df["label"] == 1].copy()
n1 = len(df1)

groups = df0["group"].unique()
G = len(groups)

# --- Base allocation ---
gcounts = df0["group"].value_counts()
base = n1 // G
alloc = gcounts.clip(upper=base).to_dict()

# --- First sampling pass ---
parts = []
for g, q in alloc.items():
    gdf = df0[df0["group"] == g]
    take = min(q, len(gdf))
    parts.append(gdf.sample(n=take, random_state=SEED, replace=False))
downsampled_0 = pd.concat(parts, ignore_index=True)

# --- Check total and fix shortfall ---
diff = n1 - len(downsampled_0)
if diff > 0:
    # take remaining from groups that still have spare capacity
    used_idx = set(downsampled_0.index)
    remaining = df0.loc[~df0.index.isin(used_idx)]
    filler = remaining.sample(n=diff, random_state=SEED, replace=False)
    downsampled_0 = pd.concat([downsampled_0, filler], ignore_index=True)

# --- Final combine ---
balanced_df = (
    pd.concat([df1, downsampled_0], ignore_index=True)
    .sample(frac=1.0, random_state=SEED)
    .reset_index(drop=True)
)

print("Balanced shape:", balanced_df.shape)
print("\nLabel counts:")
print(balanced_df["label"].value_counts())

print("\nLabel-0 group counts after downsampling:")
print(balanced_df.query("label == 0")["group"].value_counts())

# Save
save_path = "/content/drive/MyDrive/DSAProjectResults_V4/datasets/risk_cleaned.csv"
balanced_df.to_csv(save_path, index=False)
print(f"\nClean Risk set saved to: {save_path}")

"""### **Train-Test Split**
Create holdout testset to evaluate final model
"""

# === Split into 80% train and 20% test with stratified sampling by label ===
cleaned_df = pd.read_csv("/content/drive/MyDrive/DSAProjectResults_V4/datasets/risk_cleaned.csv")
print("\nCleaned dataset loaded")

train_df, test_df = train_test_split(
    cleaned_df,
    test_size=0.2,
    stratify=balanced_df["label"],
    shuffle=True,
    random_state=42
)

# Check proportions
print("\nTrain set label distribution (%):")
print(train_df["label"].value_counts(normalize=True).mul(100).round(2))

print("\nTest set label distribution (%):")
print(test_df["label"].value_counts(normalize=True).mul(100).round(2))

# Save both splits
train_path = "/content/drive/MyDrive/DSAProjectResults_V4/datasets/risk_train.csv"
test_path  = "/content/drive/MyDrive/DSAProjectResults_V4/datasets/risk_test.csv"

train_df.to_csv(train_path, index=False)
test_df.to_csv(test_path, index=False)

print(f"\nTrain set saved to: {train_path}")
print(f"Test set saved to: {test_path}")

# Verify shapes
print(f"\nTrain shape: {train_df.shape}, Test shape: {test_df.shape}")

"""# **PHASE 1: "Which is the top 3 base model?**"""

# ==========================================================
# PHASE 1 — BASE MODEL TESTING (5-FOLD CV)
# ==========================================================

# configuration
N_FOLDS = 5
BATCH_SIZE = 16
EPOCHS = 3
LR = 2e-5

# base models to test
BASE_MODELS = [
    "microsoft/deberta-v3-base",
    "roberta-base",
    "google/electra-base-discriminator",
    "distilroberta-base",
    "mental/mental-roberta-base",
    "mental/mental-bert-base-uncased"
]

# directories
DATA_PATH = os.path.join(BASE_DIR, "datasets", "risk_train.csv")
PHASE1_DIR = os.path.join(BASE_DIR, "phase1")
os.makedirs(PHASE1_DIR, exist_ok=True)

# load training data
print("Training data:", DATA_PATH)
df = pd.read_csv(DATA_PATH)
print("Dataset shape:", df.shape)
print("Label distribution (%):")
print(df["label"].value_counts(normalize=True).mul(100).round(2))

# ==========================================================
# MAIN LOOP — TRAIN BASE MODELS (5-FOLD)
# ==========================================================
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
all_results = []
model_preds_for_overlay = {}

for model_name in BASE_MODELS:
    print(f"\n{'='*60}\nTesting model: {model_name}\n{'='*60}")
    fold_metrics = []
    model_folder = os.path.join(PHASE1_DIR, model_name.replace("/", "_"))
    os.makedirs(model_folder, exist_ok=True)
    model_csv_path = os.path.join(model_folder, f"{model_name.replace('/', '_')}_phase1.csv")

    y_true_all, y_prob_all, y_pred_all = [], [], []

    for fold, (train_idx, val_idx) in enumerate(skf.split(df["text"], df["label"]), 1):
        print(f"\n--- Fold {fold}/{N_FOLDS} ---")
        train_df = df.iloc[train_idx].reset_index(drop=True)
        val_df   = df.iloc[val_idx].reset_index(drop=True)

        tokenizer = AutoTokenizer.from_pretrained(model_name)
        def tokenize_fn(batch):
            return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=256)

        train_ds = Dataset.from_pandas(train_df)
        val_ds   = Dataset.from_pandas(val_df)
        train_ds = train_ds.map(tokenize_fn, batched=True)
        val_ds   = val_ds.map(tokenize_fn, batched=True)
        train_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
        val_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

        model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

        training_args = TrainingArguments(
            output_dir=os.path.join(model_folder, f"{model_name.replace('/', '_')}_fold{fold}"),
            per_device_train_batch_size=BATCH_SIZE,
            per_device_eval_batch_size=BATCH_SIZE,
            num_train_epochs=EPOCHS,
            learning_rate=LR,
            eval_strategy="epoch",
            save_strategy="no",
            logging_dir="./logs",
            report_to="none",
            seed=SEED,
            fp16=True
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            compute_metrics=compute_metrics_trainer
        )

        trainer.train()
        raw_preds = trainer.predict(val_ds)
        preds = np.argmax(raw_preds.predictions, axis=1)
        probs = torch.softmax(torch.tensor(raw_preds.predictions), dim=1)[:, 1].numpy()
        y_true = raw_preds.label_ids

        metrics = compute_metrics_trainer(raw_preds)
        metrics["Fold"] = fold
        metrics["Model"] = model_name
        fold_metrics.append(metrics)

        y_true_all.extend(y_true)
        y_prob_all.extend(probs)
        y_pred_all.extend(preds)

    # per-model results
    fold_df = pd.DataFrame(fold_metrics)
    mean_vals = fold_df.mean(numeric_only=True).to_dict()
    mean_vals["Fold"] = "Average"
    mean_vals["Model"] = model_name
    fold_df = pd.concat([fold_df, pd.DataFrame([mean_vals])], ignore_index=True)
    fold_df.to_csv(model_csv_path, index=False)
    all_results.append(fold_df)

    # averaged plots
    y_true_all, y_prob_all, y_pred_all = np.array(y_true_all), np.array(y_prob_all), np.array(y_pred_all)
    save_eval_plots(y_true_all, y_pred_all, y_prob_all, model_name, "foldavg", model_folder)
    model_preds_for_overlay[model_name] = (y_true_all, y_prob_all)
    print(f"Saved averaged plots for {model_name} → {model_folder}")

# ==========================================================
# SAVE MASTER & SUMMARY + COMBINED ROC/PR
# ==========================================================
master_path  = os.path.join(PHASE1_DIR, "phase1_master_results.csv")
summary_path = os.path.join(PHASE1_DIR, "phase1_averaged_summary.csv")

final_df = pd.concat(all_results, ignore_index=True)
final_df.to_csv(master_path, index=False)

avg_df = final_df[final_df["Fold"] == "Average"].copy()
avg_df = avg_df.sort_values(by="Macro_F1", ascending=False).reset_index(drop=True)
avg_df.to_csv(summary_path, index=False)

# combined ROC & PR directly in /phase1/
plot_combined_curves(model_preds_for_overlay, PHASE1_DIR, curve_type="roc")
plot_combined_curves(model_preds_for_overlay, PHASE1_DIR, curve_type="pr")

print(f"\nPhase 1 complete!")
print(f"Master results → {master_path}")
print(f"Averaged summary → {summary_path}")
print(f"Combined ROC/PR saved in {PHASE1_DIR}\n")
print("Top models by  F1:")
print(avg_df[["Model", "Macro_F1", "Macro_Recall", "Accuracy", "Macro_Precision", "AUC"]])

"""# **PHASE 2: FULL FINETUNING TOP 2 MODELS**"""

# ==========================================================
# PHASE 2 — FULL FINE-TUNING + SUMMARIES + SAVED MODELS
# ==========================================================

# ----------------------------------------------------------
# CONFIG
# ----------------------------------------------------------
BASE_DIR = Path("/content/drive/MyDrive/DSAProjectResults_V4/phase2")
SAVE_MODELS_DIR = Path("/content/drive/MyDrive/DSAProjectResults_V4/saved_models")
DATA_DIR = Path("/content/drive/MyDrive/DSAProjectResults_V4/datasets")
MODELS = [
    "mental/mental-roberta-base",
    "roberta-base",
    "mental/mental-bert-base-uncased"
]
EPOCHS, BATCH_SIZE, LR, SEED, RESUME = 5, 8, 2e-5, 42, True

train_df = pd.read_csv(DATA_DIR / "risk_train.csv")
test_df = pd.read_csv(DATA_DIR / "risk_test.csv")
print(f"\n[DATA] Train: {train_df.shape}, Test: {test_df.shape}")

# ----------------------------------------------------------
# METRICS FUNCTION
# ----------------------------------------------------------
def compute_metrics(eval_pred):
    preds = np.argmax(eval_pred.predictions, axis=1)
    labels = eval_pred.label_ids
    probs = torch.softmax(torch.tensor(eval_pred.predictions), dim=1)[:, 1].numpy()
    return {
        "macro_f1": f1_score(labels, preds, average="macro"),
        "macro_recall": recall_score(labels, preds, average="macro"),
        "accuracy": accuracy_score(labels, preds),
        "roc_auc": roc_auc_score(labels, probs),
        "avg_precision": average_precision_score(labels, probs)
    }

overlay_data = {}

# ==========================================================
# MAIN LOOP — TRAIN EACH MODEL
# ==========================================================
for model_name in MODELS:
    print(f"\n{'='*70}\nFINE-TUNING MODEL: {model_name}\n{'='*70}")
    SAVE_DIR = BASE_DIR / model_name.replace("/", "_")
    SAVE_DIR.mkdir(parents=True, exist_ok=True)

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    def tokenize_fn(batch):
        return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=256)

    train_ds = Dataset.from_pandas(train_df).map(tokenize_fn, batched=True)
    test_ds = Dataset.from_pandas(test_df).map(tokenize_fn, batched=True)
    train_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
    test_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

    args = TrainingArguments(
        output_dir=str(SAVE_DIR),
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=EPOCHS,
        learning_rate=LR,
        eval_strategy="no",
        save_strategy="epoch",
        save_total_limit=3,
        logging_dir=str(SAVE_DIR / "logs"),
        report_to="none",
        seed=SEED,
        fp16=True
    )

    trainer = Trainer(model=model, args=args, train_dataset=train_ds, tokenizer=tokenizer)

    # resume if applicable
    last_ckpt = None
    if RESUME:
        checkpoints = sorted([ck for ck in SAVE_DIR.glob("checkpoint-*")], key=os.path.getmtime)
        if checkpoints:
            last_ckpt = str(checkpoints[-1])
            print(f"↪ Resuming from checkpoint → {last_ckpt}")
    trainer.train(resume_from_checkpoint=last_ckpt)

    # Evaluate
    print(f"\n[Evaluation] {model_name}")
    preds_output = trainer.predict(test_ds)
    logits = preds_output.predictions
    preds = np.argmax(logits, axis=1)
    labels = preds_output.label_ids
    probs = torch.softmax(torch.tensor(logits), dim=1)[:, 1].numpy()
    metrics = compute_metrics(preds_output)

    print("\nClassification Report:\n", classification_report(labels, preds, digits=4))
    print("Confusion Matrix:\n", confusion_matrix(labels, preds))
    print("Metrics:\n", pd.Series(metrics), "\n")

    # Save per-model metrics
    pd.DataFrame([metrics]).to_csv(SAVE_DIR / "metrics.csv", index=False)

    # ROC Curve
    fpr, tpr, _ = roc_curve(labels, probs)
    auc_val = auc(fpr, tpr)
    plt.figure(figsize=(6,6))
    plt.plot(fpr, tpr, label=f"AUC={auc_val:.3f}")
    plt.plot([0,1],[0,1],'k--',alpha=0.5)
    plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
    plt.title(f"ROC Curve — {model_name}")
    plt.legend(); plt.grid(alpha=0.3)
    plt.savefig(SAVE_DIR / "roc_curve.png", dpi=300, bbox_inches="tight"); plt.close()

    # PR Curve
    prec, rec, _ = precision_recall_curve(labels, probs)
    ap_val = average_precision_score(labels, probs)
    plt.figure(figsize=(6,6))
    plt.plot(rec, prec, label=f"AP={ap_val:.3f}")
    plt.xlabel("Recall"); plt.ylabel("Precision")
    plt.title(f"Precision–Recall Curve — {model_name}")
    plt.legend(); plt.grid(alpha=0.3)
    plt.savefig(SAVE_DIR / "pr_curve.png", dpi=300, bbox_inches="tight"); plt.close()

    # Confusion Matrix Plot
    cm = confusion_matrix(labels, preds)
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False)
    plt.xlabel("Predicted"); plt.ylabel("True")
    plt.title(f"Confusion Matrix — {model_name}")
    plt.savefig(SAVE_DIR / "confusion_matrix.png", dpi=300, bbox_inches="tight"); plt.close()

    # Save checkpoints + model to saved_models/
    FINAL_DIR = SAVE_MODELS_DIR / model_name.replace("/", "_")
    FINAL_DIR.mkdir(parents=True, exist_ok=True)
    for ckpt in SAVE_DIR.glob("checkpoint-*"):
        os.system(f'cp -r "{ckpt}" "{FINAL_DIR}/"')
    model.save_pretrained(FINAL_DIR)
    tokenizer.save_pretrained(FINAL_DIR)

    overlay_data[model_name] = {"labels": labels, "probs": probs, "metrics": metrics}

# ==========================================================
# PHASE SUMMARY + OVERLAY PLOTS
# ==========================================================
summary_path = BASE_DIR / "phase2_summary.csv"
summary_df = pd.DataFrame([
    {"Model": name, **data["metrics"]} for name, data in overlay_data.items()
]).sort_values(by="macro_f1", ascending=False).reset_index(drop=True)
summary_df.to_csv(summary_path, index=False)

print("\n[PHASE SUMMARY]")
print(summary_df)
print(f"\nSaved phase summary → {summary_path}")

# Overlay ROC
plt.figure(figsize=(7,6))
for name, d in overlay_data.items():
    fpr, tpr, _ = roc_curve(d["labels"], d["probs"])
    auc_val = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC={auc_val:.3f})")
plt.plot([0,1],[0,1],'k--',alpha=0.5)
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title("Overlay ROC Curves — Phase 2")
plt.legend(); plt.grid(alpha=0.3)
plt.savefig(BASE_DIR / "overlay_roc_curve.png", dpi=300, bbox_inches="tight"); plt.close()

# Overlay PR
plt.figure(figsize=(7,6))
for name, d in overlay_data.items():
    prec, rec, _ = precision_recall_curve(d["labels"], d["probs"])
    ap_val = average_precision_score(d["labels"], d["probs"])
    plt.plot(rec, prec, label=f"{name} (AP={ap_val:.3f})")
plt.xlabel("Recall"); plt.ylabel("Precision")
plt.title("Overlay Precision–Recall Curves — Phase 2")
plt.legend(); plt.grid(alpha=0.3)
plt.savefig(BASE_DIR / "overlay_pr_curve.png", dpi=300, bbox_inches="tight"); plt.close()

print("\n[OUTPUTS SAVED]")
print(f" Summary CSV: {summary_path}")
print(f" Overlay ROC: {BASE_DIR/'overlay_roc_curve.png'}")
print(f"Overlay PR : {BASE_DIR/'overlay_pr_curve.png'}")
print("\n Phase 2 complete! All deliverables saved and printed.")

!zip -r /content/drive/MyDrive/DSAProjectResults_V4/saved_models_backup.zip /content/drive/MyDrive/DSAProjectResults_V4/saved_models

