# -*- coding: utf-8 -*-
"""test_safetycheck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JH3q9xPdqyCk_4gRQnjCg14I8AJA8Dey
"""

# ============================================================
# Batch Test — SafetyCheck (V4)
# ============================================================

from safetycheck import SafetyCheck

# Initialize model
sc = SafetyCheck(base_dir="saved_models")

# Define grouped test texts
groups = {
    "Anxiety/Depression": [
        "I feel worthless no matter what I do",
        "My hands shake when I’m nervous",
        "Everything feels heavy and meaningless",
        "I can’t focus on anything anymore",
        "Sometimes I just cry for no reason"
    ],
    "Colloquial Suicide Terms": [
        "I'm so embarrassed I could die",
        "That exam killed me",
        "This assignment is torture",
        "My brain is dead after that lecture",
        "I bombed that test, kill me now"
    ],
    "Happy/Neutral/Sad": [
        "I had fun today",
        "Do you like strawberries?",
        "I’m feeling okay, just tired",
        "It’s been a long week but I’m fine",
        "Today was boring but peaceful"
    ],
    "Loved One’s Deaths/Suicide": [
        "My wife killed herself, I miss her so much I want to join her",
        "My brother took his life last year and I still think about it",
        "My best friend died by suicide and I feel lost",
        "It hurts to talk about my father’s suicide",
        "I lost my cousin to suicide recently"
    ],
    "Suicide Topic": [
        "I presented on suicide awareness today",
        "We discussed suicide prevention in class",
        "I’m researching suicide risk detection for my project",
        "I watched a documentary on suicide",
        "The seminar was about youth suicide"
    ],
    "Suicidal but No Intent": [
        "I want to die but I can’t bear to leave my family behind",
        "Sometimes I wish I could disappear but I’d never do it",
        "I think about dying but I know I won’t act on it",
        "I feel suicidal thoughts but I don’t want to die",
        "I want everything to stop but I can’t hurt my loved ones"
    ]
}

# Run predictions and print results
for group, texts in groups.items():
    print(f"\n{'='*60}\nGROUP: {group}\n{'='*60}")
    for text in texts:
        label, probs = sc(text, verbose=False)
        pred_str = "At Risk" if label == 1 else "Not At Risk"
        print(f"\n{text}")
        print(f"→ Prediction: {pred_str}")
        print(f"→ Probabilities: [not at risk={probs[0]:.4f}, at risk={probs[1]:.4f}]")