# -*- coding: utf-8 -*-
"""DSA4213_Safety_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ee1RjCLrPQVFgHpK5ylrWL1B6LY9JwY

### **Imports**
"""

import torch
import numpy as np
import joblib
from transformers import AutoTokenizer, AutoModelForSequenceClassification

"""### **Safety Agent Class**"""

class SafetyAgent:
    def __init__(self,
                 roberta_path="/content/finetuned_roberta/MentalRoBERTa_finetune_seed42",
                 bert_path="/content/finetuned_bert/MentalBERT_finetune_seed42",
                 tfidf_bert_vec="/content/TFIDF_+_MentalBERT_+_LogReg_vectorizer.pkl",
                 logreg_bert="/content/TFIDF_+_MentalBERT_+_LogReg_logreg.pkl",
                 tfidf_roberta_vec="/content/TFIDF_+_MentalRoBERTa_+_LogReg_vectorizer.pkl",
                 logreg_roberta="/content/TFIDF_+_MentalRoBERTa_+_LogReg_logreg.pkl"):
        """
        SafetyAgent:
        - Primary: Transformer ensemble (MentalRoBERTa + MentalBERT fine-tuned)
        - Fallback: TF-IDF + LogReg ensemble (MentalBERT + MentalRoBERTa)
        """
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # --- Load fine-tuned MentalRoBERTa ---
        self.roberta_tokenizer = AutoTokenizer.from_pretrained(roberta_path, local_files_only=True)
        self.roberta_model = AutoModelForSequenceClassification.from_pretrained(roberta_path, local_files_only=True).to(self.device)

        # --- Load fine-tuned MentalBERT ---
        self.bert_tokenizer = AutoTokenizer.from_pretrained(bert_path, local_files_only=True)
        self.bert_model = AutoModelForSequenceClassification.from_pretrained(bert_path, local_files_only=True).to(self.device)

        # --- Load fallback TF-IDF + LogReg models ---
        self.tfidf_bert = joblib.load(tfidf_bert_vec)
        self.logreg_bert = joblib.load(logreg_bert)

        self.tfidf_roberta = joblib.load(tfidf_roberta_vec)
        self.logreg_roberta = joblib.load(logreg_roberta)


    # --------------------------------------------------------
    # Transformer prediction helper
    # --------------------------------------------------------
    def predict_transformer(self, text, tokenizer, model):
        inputs = tokenizer(text, return_tensors="pt", truncation=True,
                           padding=True, max_length=256).to(self.device)
        with torch.no_grad():
            outputs = model(**inputs)
            probs = torch.softmax(outputs.logits, dim=1).cpu().numpy()
        return probs[0]


    # --------------------------------------------------------
    # TF-IDF + LogReg prediction helper
    # --------------------------------------------------------
    def predict_tfidf_logreg(self, text):
        bert_probs = self.logreg_bert.predict_proba(self.tfidf_bert.transform([text]))[0]
        roberta_probs = self.logreg_roberta.predict_proba(self.tfidf_roberta.transform([text]))[0]
        return (bert_probs + roberta_probs) / 2.0   # ensemble average


    # --------------------------------------------------------
    # Main assessment method
    # --------------------------------------------------------
    def assess(self, text, use_fallback=True):
        """
        Returns:
        - prediction: 0 = safe, 1 = at risk
        - probabilities: [prob_safe, prob_risk]
        - model_used: which model was used
        """
        try:
            # Primary: Transformer ensemble
            roberta_probs = self.predict_transformer(text, self.roberta_tokenizer, self.roberta_model)
            bert_probs = self.predict_transformer(text, self.bert_tokenizer, self.bert_model)

            avg_probs = (roberta_probs + bert_probs) / 2.0
            prediction = int(np.argmax(avg_probs))

            return {
                "prediction": prediction,
                "probabilities": avg_probs.tolist(),
                "model_used": "Transformer Ensemble (MentalRoBERTa + MentalBERT)"
            }

        except Exception as e:
            if use_fallback:
                print("⚠️ Transformers failed, using TF-IDF ensemble fallback:", e)
                probs = self.predict_tfidf_logreg(text)
                prediction = int(np.argmax(probs))
                return {
                    "prediction": prediction,
                    "probabilities": probs.tolist(),
                    "model_used": "TF-IDF Ensemble (MentalBERT + MentalRoBERTa)"
                }
            else:
                raise RuntimeError("Transformer models failed and fallback disabled.")

agent = SafetyAgent()

messages = [
    "I feel like ending it all.",
    "I'm a bit stressed with exams but I’ll manage.",
    "Life is good, I had a fun day with friends."
]

for msg in messages:
    result = agent.assess(msg)
    print(f"Message: {msg}")
    print(f"→ Prediction: {result['prediction']} | Probs: {result['probabilities']} | Model: {result['model_used']}")
    print()