# -*- coding: utf-8 -*-
"""DSA4213_Risk Classifer_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dE5vRtv_G7_vN5b_BC5Xm2kRp-1Vxmj8
"""

!pip install -U transformers datasets scikit-learn torch seaborn matplotlib huggingface_hub wandb

"""### **Logins**"""

from huggingface_hub import login
import wandb

# Hugging Face token (from https://huggingface.co/settings/tokens)
login("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")

# wandb login (from https://wandb.ai/settings)
wandb.login(key="3e353fda9cfc9be51c51fbe78068c790472b7667")

"""### **Imports**"""

from datasets import load_dataset
import pandas as pd
import numpy as np
import torch
import random

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    f1_score, accuracy_score, precision_score, recall_score,
    roc_curve, auc
)
from sklearn.preprocessing import StandardScaler, label_binarize

from transformers import (
    AutoTokenizer,
    AutoModel,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

"""### **Loading Dataset**"""

dataset = load_dataset("jingjietan/sdcnl-suicide")

TEXT_COL = "selftext"
LABEL_COL = "is_suicide"

num_labels = len(set(dataset["train"][LABEL_COL]))

train_texts = list(dataset["train"][TEXT_COL])
train_labels = list(dataset["train"][LABEL_COL])

val_texts   = list(dataset["validation"][TEXT_COL])
val_labels  = list(dataset["validation"][LABEL_COL])

test_texts  = list(dataset["test"][TEXT_COL])
test_labels = list(dataset["test"][LABEL_COL])

"""### **Results Storage**"""

from collections import defaultdict
all_results = defaultdict(list)  # stores results across seeds

"""### **Finetune Transformers**"""

def finetune_transformer(model_id, name, seed=42):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

    tokenizer = AutoTokenizer.from_pretrained(model_id)

    def tokenize(batch):
        return tokenizer(batch[TEXT_COL], padding="max_length", truncation=True, max_length=128)

    tokenized = dataset.map(tokenize, batched=True)
    tokenized = tokenized.rename_column(LABEL_COL, "labels")
    tokenized.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

    model = AutoModelForSequenceClassification.from_pretrained(model_id, num_labels=num_labels)

    args = TrainingArguments(
        output_dir=f"./results_{name}_seed{seed}",
        eval_strategy="epoch",
        save_strategy="no",
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=2,
        weight_decay=0.01,
        logging_steps=50,
        report_to="none",
        run_name=f"{name}_seed{seed}",
        seed=seed,
        fp16=torch.cuda.is_available()
    )

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = logits.argmax(axis=1)

        acc = accuracy_score(labels, preds)
        macro_f1 = f1_score(labels, preds, average="macro")
        weighted_f1 = f1_score(labels, preds, average="weighted")
        precision = precision_score(labels, preds, average="macro")
        recall = recall_score(labels, preds, average="macro")

        return {
            "accuracy": acc,
            "macro_f1": macro_f1,
            "weighted_f1": weighted_f1,
            "macro_precision": precision,
            "macro_recall": recall
        }

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=tokenized["train"],
        eval_dataset=tokenized["validation"],
        tokenizer=tokenizer,
        compute_metrics=compute_metrics
    )

    trainer.train()
    results = trainer.evaluate(tokenized["test"])

    save_path = f"./{name}_seed{seed}"
    trainer.save_model(save_path)
    tokenizer.save_pretrained(save_path)
    print(f"Saved fine-tuned model at {save_path}")

    y_true = np.array(test_labels)
    y_score = trainer.predict(tokenized["test"]).predictions

    if num_labels == 2:
        y_prob = torch.softmax(torch.tensor(y_score), dim=1).numpy()
        fpr, tpr, _ = roc_curve(y_true, y_prob[:, 1])
        roc_auc = auc(fpr, tpr)
    else:
        y_bin = label_binarize(y_true, classes=list(range(num_labels)))
        roc_auc_dict = {}
        for i in range(num_labels):
            fpr_i, tpr_i, _ = roc_curve(y_bin[:, i], y_score[:, i])
            roc_auc_dict[i] = auc(fpr_i, tpr_i)
        roc_auc = np.mean(list(roc_auc_dict.values()))

    all_results[name].append({
        "Accuracy": results["eval_accuracy"],
        "Macro-F1": results["eval_macro_f1"],
        "Weighted-F1": results["eval_weighted_f1"],
        "Macro-Precision": results["eval_macro_precision"],
        "Macro-Recall": results["eval_macro_recall"],
        "ROC-AUC": roc_auc
    })

    print(f"{name} | Seed {seed} | Macro-F1={results['eval_macro_f1']:.4f}, AUC={roc_auc:.4f}")

"""### **Extract Embeddings**"""

def get_embeddings(model_id, texts, batch_size=16):
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModel.from_pretrained(model_id)
    model.eval()
    if torch.cuda.is_available():
        model = model.to("cuda")

    all_embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        enc = tokenizer(batch, padding=True, truncation=True, return_tensors="pt", max_length=128)
        if torch.cuda.is_available():
            enc = {k: v.to("cuda") for k, v in enc.items()}
        with torch.no_grad():
            outputs = model(**enc)
            emb = outputs.last_hidden_state[:, 0, :].cpu().numpy()  # CLS token
        all_embeddings.append(emb)
    return np.vstack(all_embeddings)

"""### **Embeddings + Logistic Regression (with optional TF-IDF)**"""

def run_embeddings_logreg(model_id, name, use_tfidf=False, seed=42):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

    # === Step 1: Extract embeddings ===
    X_train = get_embeddings(model_id, train_texts)
    X_val   = get_embeddings(model_id, val_texts)
    X_test  = get_embeddings(model_id, test_texts)

    # === Step 2: Add TF-IDF features if requested ===
    if use_tfidf:
        tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
        tfidf_train = tfidf.fit_transform(train_texts).toarray()
        tfidf_val   = tfidf.transform(val_texts).toarray()
        tfidf_test  = tfidf.transform(test_texts).toarray()
        X_train = np.hstack([X_train, tfidf_train])
        X_val   = np.hstack([X_val, tfidf_val])
        X_test  = np.hstack([X_test, tfidf_test])

    # === Step 3: Standardize features ===
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val   = scaler.transform(X_val)
    X_test  = scaler.transform(X_test)

    # === Step 4: Train Logistic Regression ===
    clf = LogisticRegression(max_iter=2000, class_weight="balanced", random_state=seed)
    clf.fit(X_train, train_labels)
    y_pred = clf.predict(X_test)

    # === Step 5: Compute metrics ===
    acc = accuracy_score(test_labels, y_pred)
    macro_f1 = f1_score(test_labels, y_pred, average="macro")
    weighted_f1 = f1_score(test_labels, y_pred, average="weighted")
    precision = precision_score(test_labels, y_pred, average="macro")
    recall = recall_score(test_labels, y_pred, average="macro")

    if use_tfidf:
        import joblib
        vec_path = f"{name.replace(' ', '_')}_vectorizer.pkl"
        clf_path = f"{name.replace(' ', '_')}_logreg.pkl"
        joblib.dump(tfidf, vec_path)
        joblib.dump(clf, clf_path)
        print(f"Saved TF-IDF vectorizer to {vec_path}")
        print(f"Saved LogReg model to {clf_path}")

    # ROC-AUC
    y_true = np.array(test_labels)
    if num_labels == 2:
        y_prob = clf.predict_proba(X_test)
        fpr, tpr, _ = roc_curve(y_true, y_prob[:, 1])
        roc_auc = auc(fpr, tpr)
    else:
        y_score = clf.predict_proba(X_test)
        y_bin = label_binarize(y_true, classes=list(range(num_labels)))
        roc_auc_dict = {}
        for i in range(num_labels):
            fpr_i, tpr_i, _ = roc_curve(y_bin[:, i], y_score[:, i])
            roc_auc_dict[i] = auc(fpr_i, tpr_i)
        roc_auc = np.mean(list(roc_auc_dict.values()))

    # === Step 6: Save results ===
    all_results[name].append({
        "Accuracy": acc,
        "Macro-F1": macro_f1,
        "Weighted-F1": weighted_f1,
        "Macro-Precision": precision,
        "Macro-Recall": recall,
        "ROC-AUC": roc_auc
    })

    print(f"{name} | Seed {seed} | Macro-F1={macro_f1:.4f}, AUC={roc_auc:.4f}")

"""### **Run all 6 experiments across 5 seeds**"""

seeds = [42, 100, 123, 456, 789]

for s in seeds:
    # Fine-tuned models
    finetune_transformer("mental/mental-roberta-base", "MentalRoBERTa_finetune", seed=s)
    finetune_transformer("mental/mental-bert-base-uncased", "MentalBERT_finetune", seed=s)

    # Embeddings + LogReg
    run_embeddings_logreg("mental/mental-roberta-base", "MentalRoBERTa + LogReg", use_tfidf=False, seed=s)
    run_embeddings_logreg("mental/mental-roberta-base", "TFIDF + MentalRoBERTa + LogReg", use_tfidf=True, seed=s)
    run_embeddings_logreg("mental/mental-bert-base-uncased", "MentalBERT + LogReg", use_tfidf=False, seed=s)
    run_embeddings_logreg("mental/mental-bert-base-uncased", "TFIDF + MentalBERT + LogReg", use_tfidf=True, seed=s)

"""### **Aggregate final results**"""

summary = {}
for model, runs in all_results.items():
    df = pd.DataFrame(runs)
    summary[model] = {
        "Accuracy": f"{df['Accuracy'].mean():.4f} ± {df['Accuracy'].std():.4f}",
        "Macro-F1": f"{df['Macro-F1'].mean():.4f} ± {df['Macro-F1'].std():.4f}",
        "Weighted-F1": f"{df['Weighted-F1'].mean():.4f} ± {df['Weighted-F1'].std():.4f}",
        "Macro-Precision": f"{df['Macro-Precision'].mean():.4f} ± {df['Macro-Precision'].std():.4f}",
        "Macro-Recall": f"{df['Macro-Recall'].mean():.4f} ± {df['Macro-Recall'].std():.4f}",
        "ROC-AUC": f"{df['ROC-AUC'].mean():.4f} ± {df['ROC-AUC'].std():.4f}"
    }

summary_df = pd.DataFrame(summary).T
print("\n=== Averaged Results Across 5 Seeds (All 6 Models) ===")
print(summary_df)

"""### **Save models**"""

'''
from google.colab import drive
drive.mount('/content/drive')
'''

'''
# === Zip fine-tuned models ===
!zip -r finetuned_roberta.zip ./MentalRoBERTa_finetune_seed42
!zip -r finetuned_bert.zip ./MentalBERT_finetune_seed42

# === Download from Colab to your laptop ===
from google.colab import files
files.download("finetuned_roberta.zip")
files.download("finetuned_bert.zip")

# === Download fallback models (TF-IDF + LogReg) ===
files.download("TFIDF_+_MentalBERT_+_LogReg_vectorizer.pkl")
files.download("TFIDF_+_MentalBERT_+_LogReg_logreg.pkl")
'''

"""### **Conclusion**

### **1. MentalRoBERTa_finetune**
- best macro-f1
- very strong AUC
- best balanced model overall

### **2. MentalBERT_finetune**
- slightly lower macro-f1
- best ROC-AUC
- best model for separation, esp impt if recall of high risk posts matters more

### **3. TF-IDF + MentalBERT + LogReg**
- best among baselines (macro-f1, auc)
- solid middle ground methos when fine tuning isnt feasible

<br>
<br>

Our main model will be fine tuned MentalBERT / MentalRoBERTa, and fallback model will be TF-IDF + MentalBERT + LogReg
"""

